# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: active_sensor_device.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import sensor_pb2 as sensor__pb2

from sensor_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='active_sensor_device.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1a\x61\x63tive_sensor_device.proto\x12\x11insta360.messages\x1a\x0csensor.proto\"\x17\n\x15GetActiveSensorDevice\"b\n\x19GetActiveSensorDeviceResp\x12/\n\x06\x64\x65vice\x18\x01 \x01(\x0e\x32\x1f.insta360.messages.SensorDevice\x12\x14\n\x0cmedia_offset\x18\x02 \x01(\t\"H\n\x15SetActiveSensorDevice\x12/\n\x06\x64\x65vice\x18\x01 \x01(\x0e\x32\x1f.insta360.messages.SensorDevice\"1\n\x19SetActiveSensorDeviceResp\x12\x14\n\x0cmedia_offset\x18\x01 \x01(\tB\x08\xa2\x02\x05INSPBP\x00\x62\x06proto3'
  ,
  dependencies=[sensor__pb2.DESCRIPTOR,],
  public_dependencies=[sensor__pb2.DESCRIPTOR,])




_GETACTIVESENSORDEVICE = _descriptor.Descriptor(
  name='GetActiveSensorDevice',
  full_name='insta360.messages.GetActiveSensorDevice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=86,
)


_GETACTIVESENSORDEVICERESP = _descriptor.Descriptor(
  name='GetActiveSensorDeviceResp',
  full_name='insta360.messages.GetActiveSensorDeviceResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='device', full_name='insta360.messages.GetActiveSensorDeviceResp.device', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='media_offset', full_name='insta360.messages.GetActiveSensorDeviceResp.media_offset', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=186,
)


_SETACTIVESENSORDEVICE = _descriptor.Descriptor(
  name='SetActiveSensorDevice',
  full_name='insta360.messages.SetActiveSensorDevice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='device', full_name='insta360.messages.SetActiveSensorDevice.device', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=260,
)


_SETACTIVESENSORDEVICERESP = _descriptor.Descriptor(
  name='SetActiveSensorDeviceResp',
  full_name='insta360.messages.SetActiveSensorDeviceResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='media_offset', full_name='insta360.messages.SetActiveSensorDeviceResp.media_offset', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=311,
)

_GETACTIVESENSORDEVICERESP.fields_by_name['device'].enum_type = sensor__pb2._SENSORDEVICE
_SETACTIVESENSORDEVICE.fields_by_name['device'].enum_type = sensor__pb2._SENSORDEVICE
DESCRIPTOR.message_types_by_name['GetActiveSensorDevice'] = _GETACTIVESENSORDEVICE
DESCRIPTOR.message_types_by_name['GetActiveSensorDeviceResp'] = _GETACTIVESENSORDEVICERESP
DESCRIPTOR.message_types_by_name['SetActiveSensorDevice'] = _SETACTIVESENSORDEVICE
DESCRIPTOR.message_types_by_name['SetActiveSensorDeviceResp'] = _SETACTIVESENSORDEVICERESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetActiveSensorDevice = _reflection.GeneratedProtocolMessageType('GetActiveSensorDevice', (_message.Message,), {
  'DESCRIPTOR' : _GETACTIVESENSORDEVICE,
  '__module__' : 'active_sensor_device_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.GetActiveSensorDevice)
  })
_sym_db.RegisterMessage(GetActiveSensorDevice)

GetActiveSensorDeviceResp = _reflection.GeneratedProtocolMessageType('GetActiveSensorDeviceResp', (_message.Message,), {
  'DESCRIPTOR' : _GETACTIVESENSORDEVICERESP,
  '__module__' : 'active_sensor_device_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.GetActiveSensorDeviceResp)
  })
_sym_db.RegisterMessage(GetActiveSensorDeviceResp)

SetActiveSensorDevice = _reflection.GeneratedProtocolMessageType('SetActiveSensorDevice', (_message.Message,), {
  'DESCRIPTOR' : _SETACTIVESENSORDEVICE,
  '__module__' : 'active_sensor_device_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.SetActiveSensorDevice)
  })
_sym_db.RegisterMessage(SetActiveSensorDevice)

SetActiveSensorDeviceResp = _reflection.GeneratedProtocolMessageType('SetActiveSensorDeviceResp', (_message.Message,), {
  'DESCRIPTOR' : _SETACTIVESENSORDEVICERESP,
  '__module__' : 'active_sensor_device_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.SetActiveSensorDeviceResp)
  })
_sym_db.RegisterMessage(SetActiveSensorDeviceResp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
