# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authorization_operation_type.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='authorization_operation_type.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"authorization_operation_type.proto\x12\x11insta360.messages*C\n\x1a\x41uthorizationOperationType\x12\x0f\n\x0b\x42LE_CONNECT\x10\x00\x12\x14\n\x10WIFI_PWD_SETTING\x10\x01\x42\x08\xa2\x02\x05INSPBb\x06proto3'
)

_AUTHORIZATIONOPERATIONTYPE = _descriptor.EnumDescriptor(
  name='AuthorizationOperationType',
  full_name='insta360.messages.AuthorizationOperationType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BLE_CONNECT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WIFI_PWD_SETTING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=57,
  serialized_end=124,
)
_sym_db.RegisterEnumDescriptor(_AUTHORIZATIONOPERATIONTYPE)

AuthorizationOperationType = enum_type_wrapper.EnumTypeWrapper(_AUTHORIZATIONOPERATIONTYPE)
BLE_CONNECT = 0
WIFI_PWD_SETTING = 1


DESCRIPTOR.enum_types_by_name['AuthorizationOperationType'] = _AUTHORIZATIONOPERATIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
