# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: battery.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='battery.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rbattery.proto\x12\x11insta360.messages\"\xa4\x02\n\rBatteryStatus\x12>\n\npower_type\x18\x01 \x01(\x0e\x32*.insta360.messages.BatteryStatus.PowerType\x12\x15\n\rbattery_level\x18\x02 \x01(\r\x12\x15\n\rbattery_scale\x18\x03 \x01(\r\x12\x42\n\x0c\x62\x61ttery_type\x18\x04 \x01(\x0e\x32,.insta360.messages.BatteryStatus.BatteryType\"%\n\tPowerType\x12\x0b\n\x07\x42\x41TTERY\x10\x00\x12\x0b\n\x07\x41\x44\x41PTER\x10\x01\":\n\x0b\x42\x61tteryType\x12\t\n\x05THICK\x10\x00\x12\x08\n\x04THIN\x10\x01\x12\x0c\n\x08VERTICAL\x10\x02\x12\x08\n\x04NONE\x10\x64\x42\x08\xa2\x02\x05INSPBb\x06proto3'
)



_BATTERYSTATUS_POWERTYPE = _descriptor.EnumDescriptor(
  name='PowerType',
  full_name='insta360.messages.BatteryStatus.PowerType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BATTERY', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ADAPTER', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=232,
  serialized_end=269,
)
_sym_db.RegisterEnumDescriptor(_BATTERYSTATUS_POWERTYPE)

_BATTERYSTATUS_BATTERYTYPE = _descriptor.EnumDescriptor(
  name='BatteryType',
  full_name='insta360.messages.BatteryStatus.BatteryType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='THICK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='THIN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VERTICAL', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NONE', index=3, number=100,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=271,
  serialized_end=329,
)
_sym_db.RegisterEnumDescriptor(_BATTERYSTATUS_BATTERYTYPE)


_BATTERYSTATUS = _descriptor.Descriptor(
  name='BatteryStatus',
  full_name='insta360.messages.BatteryStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='power_type', full_name='insta360.messages.BatteryStatus.power_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='battery_level', full_name='insta360.messages.BatteryStatus.battery_level', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='battery_scale', full_name='insta360.messages.BatteryStatus.battery_scale', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='battery_type', full_name='insta360.messages.BatteryStatus.battery_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BATTERYSTATUS_POWERTYPE,
    _BATTERYSTATUS_BATTERYTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=329,
)

_BATTERYSTATUS.fields_by_name['power_type'].enum_type = _BATTERYSTATUS_POWERTYPE
_BATTERYSTATUS.fields_by_name['battery_type'].enum_type = _BATTERYSTATUS_BATTERYTYPE
_BATTERYSTATUS_POWERTYPE.containing_type = _BATTERYSTATUS
_BATTERYSTATUS_BATTERYTYPE.containing_type = _BATTERYSTATUS
DESCRIPTOR.message_types_by_name['BatteryStatus'] = _BATTERYSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BatteryStatus = _reflection.GeneratedProtocolMessageType('BatteryStatus', (_message.Message,), {
  'DESCRIPTOR' : _BATTERYSTATUS,
  '__module__' : 'battery_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.BatteryStatus)
  })
_sym_db.RegisterMessage(BatteryStatus)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
