# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bt_central.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import bluetooth_pb2 as bluetooth__pb2

from bluetooth_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='bt_central.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x62t_central.proto\x12\x11insta360.messages\x1a\x0f\x62luetooth.proto\"P\n\x10ScanBTPeripheral\x12<\n\x0fperipheral_type\x18\x01 \x01(\x0e\x32#.insta360.messages.BTPeripheralType\"L\n\x15\x43onnectToBTPeripheral\x12\x33\n\nperipheral\x18\x01 \x01(\x0b\x32\x1f.insta360.messages.BTPeripheral\"M\n\x16\x44isconnectBTPeripheral\x12\x33\n\nperipheral\x18\x01 \x01(\x0b\x32\x1f.insta360.messages.BTPeripheral\"X\n\x18GetConnectedBTPeripheral\x12<\n\x0fperipheral_type\x18\x01 \x01(\x0e\x32#.insta360.messages.BTPeripheralType\"T\n\x1cGetConnectedBTPeripheralResp\x12\x34\n\x0bperipherals\x18\x01 \x03(\x0b\x32\x1f.insta360.messages.BTPeripheralB\x08\xa2\x02\x05INSPBP\x00\x62\x06proto3'
  ,
  dependencies=[bluetooth__pb2.DESCRIPTOR,],
  public_dependencies=[bluetooth__pb2.DESCRIPTOR,])




_SCANBTPERIPHERAL = _descriptor.Descriptor(
  name='ScanBTPeripheral',
  full_name='insta360.messages.ScanBTPeripheral',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='peripheral_type', full_name='insta360.messages.ScanBTPeripheral.peripheral_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=136,
)


_CONNECTTOBTPERIPHERAL = _descriptor.Descriptor(
  name='ConnectToBTPeripheral',
  full_name='insta360.messages.ConnectToBTPeripheral',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='peripheral', full_name='insta360.messages.ConnectToBTPeripheral.peripheral', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=214,
)


_DISCONNECTBTPERIPHERAL = _descriptor.Descriptor(
  name='DisconnectBTPeripheral',
  full_name='insta360.messages.DisconnectBTPeripheral',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='peripheral', full_name='insta360.messages.DisconnectBTPeripheral.peripheral', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=293,
)


_GETCONNECTEDBTPERIPHERAL = _descriptor.Descriptor(
  name='GetConnectedBTPeripheral',
  full_name='insta360.messages.GetConnectedBTPeripheral',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='peripheral_type', full_name='insta360.messages.GetConnectedBTPeripheral.peripheral_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=295,
  serialized_end=383,
)


_GETCONNECTEDBTPERIPHERALRESP = _descriptor.Descriptor(
  name='GetConnectedBTPeripheralResp',
  full_name='insta360.messages.GetConnectedBTPeripheralResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='peripherals', full_name='insta360.messages.GetConnectedBTPeripheralResp.peripherals', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=469,
)

_SCANBTPERIPHERAL.fields_by_name['peripheral_type'].enum_type = bluetooth__pb2._BTPERIPHERALTYPE
_CONNECTTOBTPERIPHERAL.fields_by_name['peripheral'].message_type = bluetooth__pb2._BTPERIPHERAL
_DISCONNECTBTPERIPHERAL.fields_by_name['peripheral'].message_type = bluetooth__pb2._BTPERIPHERAL
_GETCONNECTEDBTPERIPHERAL.fields_by_name['peripheral_type'].enum_type = bluetooth__pb2._BTPERIPHERALTYPE
_GETCONNECTEDBTPERIPHERALRESP.fields_by_name['peripherals'].message_type = bluetooth__pb2._BTPERIPHERAL
DESCRIPTOR.message_types_by_name['ScanBTPeripheral'] = _SCANBTPERIPHERAL
DESCRIPTOR.message_types_by_name['ConnectToBTPeripheral'] = _CONNECTTOBTPERIPHERAL
DESCRIPTOR.message_types_by_name['DisconnectBTPeripheral'] = _DISCONNECTBTPERIPHERAL
DESCRIPTOR.message_types_by_name['GetConnectedBTPeripheral'] = _GETCONNECTEDBTPERIPHERAL
DESCRIPTOR.message_types_by_name['GetConnectedBTPeripheralResp'] = _GETCONNECTEDBTPERIPHERALRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ScanBTPeripheral = _reflection.GeneratedProtocolMessageType('ScanBTPeripheral', (_message.Message,), {
  'DESCRIPTOR' : _SCANBTPERIPHERAL,
  '__module__' : 'bt_central_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.ScanBTPeripheral)
  })
_sym_db.RegisterMessage(ScanBTPeripheral)

ConnectToBTPeripheral = _reflection.GeneratedProtocolMessageType('ConnectToBTPeripheral', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTTOBTPERIPHERAL,
  '__module__' : 'bt_central_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.ConnectToBTPeripheral)
  })
_sym_db.RegisterMessage(ConnectToBTPeripheral)

DisconnectBTPeripheral = _reflection.GeneratedProtocolMessageType('DisconnectBTPeripheral', (_message.Message,), {
  'DESCRIPTOR' : _DISCONNECTBTPERIPHERAL,
  '__module__' : 'bt_central_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.DisconnectBTPeripheral)
  })
_sym_db.RegisterMessage(DisconnectBTPeripheral)

GetConnectedBTPeripheral = _reflection.GeneratedProtocolMessageType('GetConnectedBTPeripheral', (_message.Message,), {
  'DESCRIPTOR' : _GETCONNECTEDBTPERIPHERAL,
  '__module__' : 'bt_central_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.GetConnectedBTPeripheral)
  })
_sym_db.RegisterMessage(GetConnectedBTPeripheral)

GetConnectedBTPeripheralResp = _reflection.GeneratedProtocolMessageType('GetConnectedBTPeripheralResp', (_message.Message,), {
  'DESCRIPTOR' : _GETCONNECTEDBTPERIPHERALRESP,
  '__module__' : 'bt_central_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.GetConnectedBTPeripheralResp)
  })
_sym_db.RegisterMessage(GetConnectedBTPeripheralResp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
