# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calibrate_gyro.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calibrate_gyro.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x63\x61librate_gyro.proto\x12\x11insta360.messages\"#\n\rCalibrateGyro\x12\x12\n\ngyro_count\x18\x01 \x01(\rB\x08\xa2\x02\x05INSPBb\x06proto3'
)




_CALIBRATEGYRO = _descriptor.Descriptor(
  name='CalibrateGyro',
  full_name='insta360.messages.CalibrateGyro',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gyro_count', full_name='insta360.messages.CalibrateGyro.gyro_count', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['CalibrateGyro'] = _CALIBRATEGYRO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CalibrateGyro = _reflection.GeneratedProtocolMessageType('CalibrateGyro', (_message.Message,), {
  'DESCRIPTOR' : _CALIBRATEGYRO,
  '__module__' : 'calibrate_gyro_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.CalibrateGyro)
  })
_sym_db.RegisterMessage(CalibrateGyro)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
