# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: capture_auto_split.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import video_pb2 as video__pb2

from video_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='capture_auto_split.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18\x63\x61pture_auto_split.proto\x12\x11insta360.messages\x1a\x0bvideo.proto\"G\n\x1cNotificationCaptureAutoSplit\x12\'\n\x05video\x18\x01 \x01(\x0b\x32\x18.insta360.messages.VideoB\x08\xa2\x02\x05INSPBP\x00\x62\x06proto3'
  ,
  dependencies=[video__pb2.DESCRIPTOR,],
  public_dependencies=[video__pb2.DESCRIPTOR,])




_NOTIFICATIONCAPTUREAUTOSPLIT = _descriptor.Descriptor(
  name='NotificationCaptureAutoSplit',
  full_name='insta360.messages.NotificationCaptureAutoSplit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='video', full_name='insta360.messages.NotificationCaptureAutoSplit.video', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=131,
)

_NOTIFICATIONCAPTUREAUTOSPLIT.fields_by_name['video'].message_type = video__pb2._VIDEO
DESCRIPTOR.message_types_by_name['NotificationCaptureAutoSplit'] = _NOTIFICATIONCAPTUREAUTOSPLIT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NotificationCaptureAutoSplit = _reflection.GeneratedProtocolMessageType('NotificationCaptureAutoSplit', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONCAPTUREAUTOSPLIT,
  '__module__' : 'capture_auto_split_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.NotificationCaptureAutoSplit)
  })
_sym_db.RegisterMessage(NotificationCaptureAutoSplit)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
