# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chargebox.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import battery_pb2 as battery__pb2

from battery_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='chargebox.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x63hargebox.proto\x12\x11insta360.messages\x1a\rbattery.proto\"\xe9\x05\n\x18\x43hargeboxConnectedStatus\x12\x65\n\x19\x63hargebox_connected_state\x18\x01 \x01(\x0e\x32\x42.insta360.messages.ChargeboxConnectedStatus.ChargeboxConnectedType\x12\x44\n\x1a\x63hargingbox_battery_status\x18\x02 \x01(\x0b\x32 .insta360.messages.BatteryStatus\x12^\n\x16\x63hargebox_onoff_status\x18\x03 \x01(\x0e\x32>.insta360.messages.ChargeboxConnectedStatus.ChargeboxOnOffInfo\x12n\n\x1d\x63hargebox_usb_connected_state\x18\x04 \x01(\x0e\x32G.insta360.messages.ChargeboxConnectedStatus.ChargeboxUsbBtConnectedType\x12m\n\x1c\x63hargebox_bt_connected_state\x18\x05 \x01(\x0e\x32G.insta360.messages.ChargeboxConnectedStatus.ChargeboxUsbBtConnectedType\"9\n\x16\x43hargeboxConnectedType\x12\x10\n\x0c\x64isconnected\x10\x00\x12\r\n\tconnected\x10\x01\"-\n\x12\x43hargeboxOnOffInfo\x12\x0b\n\x07offline\x10\x00\x12\n\n\x06online\x10\x01\"w\n\x1b\x43hargeboxUsbBtConnectedType\x12\x1b\n\x17usb_bt_status_undefined\x10\x00\x12\x1e\n\x1ausb_bt_status_disconnected\x10\x01\x12\x1b\n\x17usb_bt_status_connected\x10\x02\x42\x08\xa2\x02\x05INSPBP\x00\x62\x06proto3'
  ,
  dependencies=[battery__pb2.DESCRIPTOR,],
  public_dependencies=[battery__pb2.DESCRIPTOR,])



_CHARGEBOXCONNECTEDSTATUS_CHARGEBOXCONNECTEDTYPE = _descriptor.EnumDescriptor(
  name='ChargeboxConnectedType',
  full_name='insta360.messages.ChargeboxConnectedStatus.ChargeboxConnectedType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='disconnected', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='connected', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=574,
  serialized_end=631,
)
_sym_db.RegisterEnumDescriptor(_CHARGEBOXCONNECTEDSTATUS_CHARGEBOXCONNECTEDTYPE)

_CHARGEBOXCONNECTEDSTATUS_CHARGEBOXONOFFINFO = _descriptor.EnumDescriptor(
  name='ChargeboxOnOffInfo',
  full_name='insta360.messages.ChargeboxConnectedStatus.ChargeboxOnOffInfo',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='offline', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='online', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=633,
  serialized_end=678,
)
_sym_db.RegisterEnumDescriptor(_CHARGEBOXCONNECTEDSTATUS_CHARGEBOXONOFFINFO)

_CHARGEBOXCONNECTEDSTATUS_CHARGEBOXUSBBTCONNECTEDTYPE = _descriptor.EnumDescriptor(
  name='ChargeboxUsbBtConnectedType',
  full_name='insta360.messages.ChargeboxConnectedStatus.ChargeboxUsbBtConnectedType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='usb_bt_status_undefined', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='usb_bt_status_disconnected', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='usb_bt_status_connected', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=680,
  serialized_end=799,
)
_sym_db.RegisterEnumDescriptor(_CHARGEBOXCONNECTEDSTATUS_CHARGEBOXUSBBTCONNECTEDTYPE)


_CHARGEBOXCONNECTEDSTATUS = _descriptor.Descriptor(
  name='ChargeboxConnectedStatus',
  full_name='insta360.messages.ChargeboxConnectedStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chargebox_connected_state', full_name='insta360.messages.ChargeboxConnectedStatus.chargebox_connected_state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chargingbox_battery_status', full_name='insta360.messages.ChargeboxConnectedStatus.chargingbox_battery_status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chargebox_onoff_status', full_name='insta360.messages.ChargeboxConnectedStatus.chargebox_onoff_status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chargebox_usb_connected_state', full_name='insta360.messages.ChargeboxConnectedStatus.chargebox_usb_connected_state', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chargebox_bt_connected_state', full_name='insta360.messages.ChargeboxConnectedStatus.chargebox_bt_connected_state', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CHARGEBOXCONNECTEDSTATUS_CHARGEBOXCONNECTEDTYPE,
    _CHARGEBOXCONNECTEDSTATUS_CHARGEBOXONOFFINFO,
    _CHARGEBOXCONNECTEDSTATUS_CHARGEBOXUSBBTCONNECTEDTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=799,
)

_CHARGEBOXCONNECTEDSTATUS.fields_by_name['chargebox_connected_state'].enum_type = _CHARGEBOXCONNECTEDSTATUS_CHARGEBOXCONNECTEDTYPE
_CHARGEBOXCONNECTEDSTATUS.fields_by_name['chargingbox_battery_status'].message_type = battery__pb2._BATTERYSTATUS
_CHARGEBOXCONNECTEDSTATUS.fields_by_name['chargebox_onoff_status'].enum_type = _CHARGEBOXCONNECTEDSTATUS_CHARGEBOXONOFFINFO
_CHARGEBOXCONNECTEDSTATUS.fields_by_name['chargebox_usb_connected_state'].enum_type = _CHARGEBOXCONNECTEDSTATUS_CHARGEBOXUSBBTCONNECTEDTYPE
_CHARGEBOXCONNECTEDSTATUS.fields_by_name['chargebox_bt_connected_state'].enum_type = _CHARGEBOXCONNECTEDSTATUS_CHARGEBOXUSBBTCONNECTEDTYPE
_CHARGEBOXCONNECTEDSTATUS_CHARGEBOXCONNECTEDTYPE.containing_type = _CHARGEBOXCONNECTEDSTATUS
_CHARGEBOXCONNECTEDSTATUS_CHARGEBOXONOFFINFO.containing_type = _CHARGEBOXCONNECTEDSTATUS
_CHARGEBOXCONNECTEDSTATUS_CHARGEBOXUSBBTCONNECTEDTYPE.containing_type = _CHARGEBOXCONNECTEDSTATUS
DESCRIPTOR.message_types_by_name['ChargeboxConnectedStatus'] = _CHARGEBOXCONNECTEDSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChargeboxConnectedStatus = _reflection.GeneratedProtocolMessageType('ChargeboxConnectedStatus', (_message.Message,), {
  'DESCRIPTOR' : _CHARGEBOXCONNECTEDSTATUS,
  '__module__' : 'chargebox_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.ChargeboxConnectedStatus)
  })
_sym_db.RegisterMessage(ChargeboxConnectedStatus)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
