# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: charging_command_type.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='charging_command_type.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1b\x63harging_command_type.proto\x12\x11insta360.messages*\xb9\x02\n\x13\x43hargingMessageCode\x12\x11\n\rFAC_OLED_TEST\x10\x00\x12\x15\n\x11\x46\x41\x43_OLED_ROW_EVEN\x10\x01\x12\x17\n\x13\x46\x41\x43_OLED_ROW_UNEVEN\x10\x02\x12\x16\n\x12\x46\x41\x43_OLED_LINE_EVEN\x10\x03\x12\x18\n\x14\x46\x41\x43_OLED_LINE_UNEVEN\x10\x04\x12\x10\n\x0c\x46\x41\x43_LED_TEST\x10\x05\x12\x14\n\x10\x46\x41\x43_DEVLINK_TEST\x10\x06\x12\x13\n\x0f\x46\x41\x43_BUTTON_TEST\x10\x07\x12\x1b\n\x17\x46\x41\x43_NORMAL_MODE_REFRESH\x10\x08\x12\x11\n\rFAC_HALL_TEST\x10\t\x12\x16\n\x12\x46\x41\x43_BLUETOOTH_TEST\x10\x10\x12\x1b\n\x17\x46\x41\x43_BLUETOOTH_WKUP_TEST\x10\x11\x12\x0b\n\x07\x46\x41\x43_NUM\x10\x12\x42\x08\xa2\x02\x05INSPBb\x06proto3'
)

_CHARGINGMESSAGECODE = _descriptor.EnumDescriptor(
  name='ChargingMessageCode',
  full_name='insta360.messages.ChargingMessageCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FAC_OLED_TEST', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAC_OLED_ROW_EVEN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAC_OLED_ROW_UNEVEN', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAC_OLED_LINE_EVEN', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAC_OLED_LINE_UNEVEN', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAC_LED_TEST', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAC_DEVLINK_TEST', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAC_BUTTON_TEST', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAC_NORMAL_MODE_REFRESH', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAC_HALL_TEST', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAC_BLUETOOTH_TEST', index=10, number=16,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAC_BLUETOOTH_WKUP_TEST', index=11, number=17,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAC_NUM', index=12, number=18,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=51,
  serialized_end=364,
)
_sym_db.RegisterEnumDescriptor(_CHARGINGMESSAGECODE)

ChargingMessageCode = enum_type_wrapper.EnumTypeWrapper(_CHARGINGMESSAGECODE)
FAC_OLED_TEST = 0
FAC_OLED_ROW_EVEN = 1
FAC_OLED_ROW_UNEVEN = 2
FAC_OLED_LINE_EVEN = 3
FAC_OLED_LINE_UNEVEN = 4
FAC_LED_TEST = 5
FAC_DEVLINK_TEST = 6
FAC_BUTTON_TEST = 7
FAC_NORMAL_MODE_REFRESH = 8
FAC_HALL_TEST = 9
FAC_BLUETOOTH_TEST = 16
FAC_BLUETOOTH_WKUP_TEST = 17
FAC_NUM = 18


DESCRIPTOR.enum_types_by_name['ChargingMessageCode'] = _CHARGINGMESSAGECODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
