# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: close_camera_oled.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='close_camera_oled.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x63lose_camera_oled.proto\x12\x11insta360.messages\"\x11\n\x0f\x43loseCameraOled\"\x15\n\x13\x43loseCameraOledRespB\x08\xa2\x02\x05INSPBb\x06proto3'
)




_CLOSECAMERAOLED = _descriptor.Descriptor(
  name='CloseCameraOled',
  full_name='insta360.messages.CloseCameraOled',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=63,
)


_CLOSECAMERAOLEDRESP = _descriptor.Descriptor(
  name='CloseCameraOledResp',
  full_name='insta360.messages.CloseCameraOledResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['CloseCameraOled'] = _CLOSECAMERAOLED
DESCRIPTOR.message_types_by_name['CloseCameraOledResp'] = _CLOSECAMERAOLEDRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CloseCameraOled = _reflection.GeneratedProtocolMessageType('CloseCameraOled', (_message.Message,), {
  'DESCRIPTOR' : _CLOSECAMERAOLED,
  '__module__' : 'close_camera_oled_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.CloseCameraOled)
  })
_sym_db.RegisterMessage(CloseCameraOled)

CloseCameraOledResp = _reflection.GeneratedProtocolMessageType('CloseCameraOledResp', (_message.Message,), {
  'DESCRIPTOR' : _CLOSECAMERAOLEDRESP,
  '__module__' : 'close_camera_oled_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.CloseCameraOledResp)
  })
_sym_db.RegisterMessage(CloseCameraOledResp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
