# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: delete_files.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='delete_files.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x64\x65lete_files.proto\x12\x11insta360.messages\"\x1a\n\x0b\x44\x65leteFiles\x12\x0b\n\x03uri\x18\x01 \x03(\t\"#\n\x0f\x44\x65leteFilesResp\x12\x10\n\x08\x66\x61il_uri\x18\x01 \x03(\tB\x08\xa2\x02\x05INSPBb\x06proto3'
)




_DELETEFILES = _descriptor.Descriptor(
  name='DeleteFiles',
  full_name='insta360.messages.DeleteFiles',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='insta360.messages.DeleteFiles.uri', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=67,
)


_DELETEFILESRESP = _descriptor.Descriptor(
  name='DeleteFilesResp',
  full_name='insta360.messages.DeleteFilesResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fail_uri', full_name='insta360.messages.DeleteFilesResp.fail_uri', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=104,
)

DESCRIPTOR.message_types_by_name['DeleteFiles'] = _DELETEFILES
DESCRIPTOR.message_types_by_name['DeleteFilesResp'] = _DELETEFILESRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeleteFiles = _reflection.GeneratedProtocolMessageType('DeleteFiles', (_message.Message,), {
  'DESCRIPTOR' : _DELETEFILES,
  '__module__' : 'delete_files_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.DeleteFiles)
  })
_sym_db.RegisterMessage(DeleteFiles)

DeleteFilesResp = _reflection.GeneratedProtocolMessageType('DeleteFilesResp', (_message.Message,), {
  'DESCRIPTOR' : _DELETEFILESRESP,
  '__module__' : 'delete_files_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.DeleteFilesResp)
  })
_sym_db.RegisterMessage(DeleteFilesResp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
