# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: detect_face.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='detect_face.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x64\x65tect_face.proto\x12\x11insta360.messages\"/\n\x16NotificationDetectFace\x12\x15\n\rdetectFaceNum\x18\x01 \x01(\rB\x08\xa2\x02\x05INSPBb\x06proto3'
)




_NOTIFICATIONDETECTFACE = _descriptor.Descriptor(
  name='NotificationDetectFace',
  full_name='insta360.messages.NotificationDetectFace',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='detectFaceNum', full_name='insta360.messages.NotificationDetectFace.detectFaceNum', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=87,
)

DESCRIPTOR.message_types_by_name['NotificationDetectFace'] = _NOTIFICATIONDETECTFACE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NotificationDetectFace = _reflection.GeneratedProtocolMessageType('NotificationDetectFace', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONDETECTFACE,
  '__module__' : 'detect_face_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.NotificationDetectFace)
  })
_sym_db.RegisterMessage(NotificationDetectFace)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
