# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exposure.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='exposure.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x65xposure.proto\x12\x11insta360.messages\"\xc9\x01\n\x0f\x45xposureOptions\x12;\n\x07program\x18\x01 \x01(\x0e\x32*.insta360.messages.ExposureOptions.Program\x12\x0b\n\x03iso\x18\x02 \x01(\r\x12\x15\n\rshutter_speed\x18\x03 \x01(\x01\"U\n\x07Program\x12\x08\n\x04\x41UTO\x10\x00\x12\x10\n\x0cISO_PRIORITY\x10\x01\x12\x14\n\x10SHUTTER_PRIORITY\x10\x02\x12\n\n\x06MANUAL\x10\x03\x12\x0c\n\x08\x41\x44\x41PTIVE\x10\x04\x42\x08\xa2\x02\x05INSPBb\x06proto3'
)



_EXPOSUREOPTIONS_PROGRAM = _descriptor.EnumDescriptor(
  name='Program',
  full_name='insta360.messages.ExposureOptions.Program',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AUTO', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ISO_PRIORITY', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHUTTER_PRIORITY', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MANUAL', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ADAPTIVE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=154,
  serialized_end=239,
)
_sym_db.RegisterEnumDescriptor(_EXPOSUREOPTIONS_PROGRAM)


_EXPOSUREOPTIONS = _descriptor.Descriptor(
  name='ExposureOptions',
  full_name='insta360.messages.ExposureOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='program', full_name='insta360.messages.ExposureOptions.program', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='iso', full_name='insta360.messages.ExposureOptions.iso', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shutter_speed', full_name='insta360.messages.ExposureOptions.shutter_speed', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EXPOSUREOPTIONS_PROGRAM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=239,
)

_EXPOSUREOPTIONS.fields_by_name['program'].enum_type = _EXPOSUREOPTIONS_PROGRAM
_EXPOSUREOPTIONS_PROGRAM.containing_type = _EXPOSUREOPTIONS
DESCRIPTOR.message_types_by_name['ExposureOptions'] = _EXPOSUREOPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExposureOptions = _reflection.GeneratedProtocolMessageType('ExposureOptions', (_message.Message,), {
  'DESCRIPTOR' : _EXPOSUREOPTIONS,
  '__module__' : 'exposure_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.ExposureOptions)
  })
_sym_db.RegisterMessage(ExposureOptions)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
