# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fileinfo_list.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fileinfo_list.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x66ileinfo_list.proto\x12\x11insta360.messages\"/\n\x08\x46ileInfo\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x10\n\x08metadata\x18\x02 \x01(\x0c\"?\n\rFileInfo_List\x12.\n\tfile_info\x18\x01 \x03(\x0b\x32\x1b.insta360.messages.FileInfoB\x08\xa2\x02\x05INSPBb\x06proto3'
)




_FILEINFO = _descriptor.Descriptor(
  name='FileInfo',
  full_name='insta360.messages.FileInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_path', full_name='insta360.messages.FileInfo.file_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='insta360.messages.FileInfo.metadata', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=89,
)


_FILEINFO_LIST = _descriptor.Descriptor(
  name='FileInfo_List',
  full_name='insta360.messages.FileInfo_List',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_info', full_name='insta360.messages.FileInfo_List.file_info', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=154,
)

_FILEINFO_LIST.fields_by_name['file_info'].message_type = _FILEINFO
DESCRIPTOR.message_types_by_name['FileInfo'] = _FILEINFO
DESCRIPTOR.message_types_by_name['FileInfo_List'] = _FILEINFO_LIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FileInfo = _reflection.GeneratedProtocolMessageType('FileInfo', (_message.Message,), {
  'DESCRIPTOR' : _FILEINFO,
  '__module__' : 'fileinfo_list_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.FileInfo)
  })
_sym_db.RegisterMessage(FileInfo)

FileInfo_List = _reflection.GeneratedProtocolMessageType('FileInfo_List', (_message.Message,), {
  'DESCRIPTOR' : _FILEINFO_LIST,
  '__module__' : 'fileinfo_list_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.FileInfo_List)
  })
_sym_db.RegisterMessage(FileInfo_List)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
