# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fw_upgrade_state.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fw_upgrade_state.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x66w_upgrade_state.proto\x12\x11insta360.messages\"\xe3\x07\n\x13UpgradeStateOptions\x12\x43\n\x05state\x18\x01 \x01(\x0e\x32\x34.insta360.messages.UpgradeStateOptions.Upgrage_State\x12H\n\nerror_code\x18\x02 \x01(\x0e\x32\x34.insta360.messages.UpgradeStateOptions.Upgrage_State\"\xbc\x06\n\rUpgrage_State\x12\x16\n\x12UPGRADE_STATE_IDLE\x10\x00\x12\x1c\n\x18UPGRADE_STATE_PRE_NOFILE\x10\x01\x12%\n!UPGRADE_STATE_GET_FILE_LIST_ERROR\x10\x02\x12\"\n\x1eUPGRADE_STATE_PRE_CAME_NOPOWER\x10\x03\x12\"\n\x1eUPGRADE_STATE_PRE_CASE_NOPOWER\x10\x04\x12\x1c\n\x18UPGRADE_STATE_ING_UNPACK\x10\x05\x12\"\n\x1eUPGRADE_STATE_ING_UNPACK_ERROR\x10\x06\x12%\n!UPGRADE_STATE_ING_CHECK_MD5_ERROR\x10\x07\x12#\n\x1fUPGRADE_STATE_ING_CASE_FW_START\x10\x08\x12#\n\x1fUPGRADE_STATE_ING_CASE_FW_ERROR\x10\t\x12&\n\"UPGRADE_STATE_ING_CASE_BT_FW_START\x10\n\x12&\n\"UPGRADE_STATE_ING_CASE_BT_FW_ERROR\x10\x0b\x12&\n\"UPGRADE_STATE_ING_CAME_BT_FW_START\x10\x0c\x12&\n\"UPGRADE_STATE_ING_CAME_BT_FW_ERROR\x10\r\x12#\n\x1fUPGRADE_STATE_ING_CAME_FW_START\x10\x0e\x12\'\n#UPGRADE_STATE_VERSION_CHECK_SUCCESS\x10\x0f\x12&\n\"UPGRADE_STATE_VERSION_CHECK_FAILED\x10\x10\x12\x1f\n\x1bUPGRADE_STATE_ING_FW_UPLOAD\x10\x11\x12\"\n\x1eUPGRADE_STATE_FW_UPLOAD_FAILED\x10\x12\x12#\n\x1fUPGRADE_STATE_FW_UPLOAD_SUCCESS\x10\x13\x12)\n%UPGRADE_STATE_PRE_USB_SHAKEHANDS_FAIL\x10\x14\x12(\n$UPGRADE_STATE_PRE_BT_SHAKEHANDS_FAIL\x10\x15\x42\x08\xa2\x02\x05INSPBb\x06proto3'
)



_UPGRADESTATEOPTIONS_UPGRAGE_STATE = _descriptor.EnumDescriptor(
  name='Upgrage_State',
  full_name='insta360.messages.UpgradeStateOptions.Upgrage_State',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UPGRADE_STATE_IDLE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UPGRADE_STATE_PRE_NOFILE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UPGRADE_STATE_GET_FILE_LIST_ERROR', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UPGRADE_STATE_PRE_CAME_NOPOWER', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UPGRADE_STATE_PRE_CASE_NOPOWER', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UPGRADE_STATE_ING_UNPACK', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UPGRADE_STATE_ING_UNPACK_ERROR', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UPGRADE_STATE_ING_CHECK_MD5_ERROR', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UPGRADE_STATE_ING_CASE_FW_START', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UPGRADE_STATE_ING_CASE_FW_ERROR', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UPGRADE_STATE_ING_CASE_BT_FW_START', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UPGRADE_STATE_ING_CASE_BT_FW_ERROR', index=11, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UPGRADE_STATE_ING_CAME_BT_FW_START', index=12, number=12,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UPGRADE_STATE_ING_CAME_BT_FW_ERROR', index=13, number=13,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UPGRADE_STATE_ING_CAME_FW_START', index=14, number=14,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UPGRADE_STATE_VERSION_CHECK_SUCCESS', index=15, number=15,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UPGRADE_STATE_VERSION_CHECK_FAILED', index=16, number=16,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UPGRADE_STATE_ING_FW_UPLOAD', index=17, number=17,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UPGRADE_STATE_FW_UPLOAD_FAILED', index=18, number=18,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UPGRADE_STATE_FW_UPLOAD_SUCCESS', index=19, number=19,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UPGRADE_STATE_PRE_USB_SHAKEHANDS_FAIL', index=20, number=20,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UPGRADE_STATE_PRE_BT_SHAKEHANDS_FAIL', index=21, number=21,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=213,
  serialized_end=1041,
)
_sym_db.RegisterEnumDescriptor(_UPGRADESTATEOPTIONS_UPGRAGE_STATE)


_UPGRADESTATEOPTIONS = _descriptor.Descriptor(
  name='UpgradeStateOptions',
  full_name='insta360.messages.UpgradeStateOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='insta360.messages.UpgradeStateOptions.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='insta360.messages.UpgradeStateOptions.error_code', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _UPGRADESTATEOPTIONS_UPGRAGE_STATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=1041,
)

_UPGRADESTATEOPTIONS.fields_by_name['state'].enum_type = _UPGRADESTATEOPTIONS_UPGRAGE_STATE
_UPGRADESTATEOPTIONS.fields_by_name['error_code'].enum_type = _UPGRADESTATEOPTIONS_UPGRAGE_STATE
_UPGRADESTATEOPTIONS_UPGRAGE_STATE.containing_type = _UPGRADESTATEOPTIONS
DESCRIPTOR.message_types_by_name['UpgradeStateOptions'] = _UPGRADESTATEOPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpgradeStateOptions = _reflection.GeneratedProtocolMessageType('UpgradeStateOptions', (_message.Message,), {
  'DESCRIPTOR' : _UPGRADESTATEOPTIONS,
  '__module__' : 'fw_upgrade_state_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.UpgradeStateOptions)
  })
_sym_db.RegisterMessage(UpgradeStateOptions)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
