# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_options.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import options_pb2 as options__pb2
try:
  photo__pb2 = options__pb2.photo__pb2
except AttributeError:
  photo__pb2 = options__pb2.photo_pb2
try:
  video__pb2 = options__pb2.video__pb2
except AttributeError:
  video__pb2 = options__pb2.video_pb2
try:
  battery__pb2 = options__pb2.battery__pb2
except AttributeError:
  battery__pb2 = options__pb2.battery_pb2
try:
  storage__pb2 = options__pb2.storage__pb2
except AttributeError:
  storage__pb2 = options__pb2.storage_pb2
try:
  button__press__pb2 = options__pb2.button__press__pb2
except AttributeError:
  button__press__pb2 = options__pb2.button_press_pb2
try:
  flicker__pb2 = options__pb2.flicker__pb2
except AttributeError:
  flicker__pb2 = options__pb2.flicker_pb2
try:
  sensor__pb2 = options__pb2.sensor__pb2
except AttributeError:
  sensor__pb2 = options__pb2.sensor_pb2
try:
  chargebox__pb2 = options__pb2.chargebox__pb2
except AttributeError:
  chargebox__pb2 = options__pb2.chargebox_pb2
try:
  battery__pb2 = options__pb2.battery__pb2
except AttributeError:
  battery__pb2 = options__pb2.battery_pb2
try:
  offset__state__pb2 = options__pb2.offset__state__pb2
except AttributeError:
  offset__state__pb2 = options__pb2.offset_state_pb2
try:
  window__crop__info__pb2 = options__pb2.window__crop__info__pb2
except AttributeError:
  window__crop__info__pb2 = options__pb2.window_crop_info_pb2

from options_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='get_options.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11get_options.proto\x12\x11insta360.messages\x1a\roptions.proto\"A\n\nGetOptions\x12\x33\n\x0coption_types\x18\x01 \x03(\x0e\x32\x1d.insta360.messages.OptionType\"p\n\x0eGetOptionsResp\x12\x33\n\x0coption_types\x18\x01 \x03(\x0e\x32\x1d.insta360.messages.OptionType\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.insta360.messages.OptionsB\x08\xa2\x02\x05INSPBP\x00\x62\x06proto3'
  ,
  dependencies=[options__pb2.DESCRIPTOR,],
  public_dependencies=[options__pb2.DESCRIPTOR,])




_GETOPTIONS = _descriptor.Descriptor(
  name='GetOptions',
  full_name='insta360.messages.GetOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='option_types', full_name='insta360.messages.GetOptions.option_types', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=120,
)


_GETOPTIONSRESP = _descriptor.Descriptor(
  name='GetOptionsResp',
  full_name='insta360.messages.GetOptionsResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='option_types', full_name='insta360.messages.GetOptionsResp.option_types', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='insta360.messages.GetOptionsResp.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=234,
)

_GETOPTIONS.fields_by_name['option_types'].enum_type = options__pb2._OPTIONTYPE
_GETOPTIONSRESP.fields_by_name['option_types'].enum_type = options__pb2._OPTIONTYPE
_GETOPTIONSRESP.fields_by_name['value'].message_type = options__pb2._OPTIONS
DESCRIPTOR.message_types_by_name['GetOptions'] = _GETOPTIONS
DESCRIPTOR.message_types_by_name['GetOptionsResp'] = _GETOPTIONSRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetOptions = _reflection.GeneratedProtocolMessageType('GetOptions', (_message.Message,), {
  'DESCRIPTOR' : _GETOPTIONS,
  '__module__' : 'get_options_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.GetOptions)
  })
_sym_db.RegisterMessage(GetOptions)

GetOptionsResp = _reflection.GeneratedProtocolMessageType('GetOptionsResp', (_message.Message,), {
  'DESCRIPTOR' : _GETOPTIONSRESP,
  '__module__' : 'get_options_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.GetOptionsResp)
  })
_sym_db.RegisterMessage(GetOptionsResp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
