# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_wifi_connection_info.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import wifi_connection_info_pb2 as wifi__connection__info__pb2

from wifi_connection_info_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='get_wifi_connection_info.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1eget_wifi_connection_info.proto\x12\x11insta360.messages\x1a\x1awifi_connection_info.proto\"\x17\n\x15GetWifiConnectionInfo\"`\n\x19GetWifiConnectionInfoResp\x12\x43\n\x14wifi_connection_info\x18\x01 \x01(\x0b\x32%.insta360.messages.WifiConnectionInfoB\x08\xa2\x02\x05INSPBP\x00\x62\x06proto3'
  ,
  dependencies=[wifi__connection__info__pb2.DESCRIPTOR,],
  public_dependencies=[wifi__connection__info__pb2.DESCRIPTOR,])




_GETWIFICONNECTIONINFO = _descriptor.Descriptor(
  name='GetWifiConnectionInfo',
  full_name='insta360.messages.GetWifiConnectionInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=104,
)


_GETWIFICONNECTIONINFORESP = _descriptor.Descriptor(
  name='GetWifiConnectionInfoResp',
  full_name='insta360.messages.GetWifiConnectionInfoResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='wifi_connection_info', full_name='insta360.messages.GetWifiConnectionInfoResp.wifi_connection_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=202,
)

_GETWIFICONNECTIONINFORESP.fields_by_name['wifi_connection_info'].message_type = wifi__connection__info__pb2._WIFICONNECTIONINFO
DESCRIPTOR.message_types_by_name['GetWifiConnectionInfo'] = _GETWIFICONNECTIONINFO
DESCRIPTOR.message_types_by_name['GetWifiConnectionInfoResp'] = _GETWIFICONNECTIONINFORESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetWifiConnectionInfo = _reflection.GeneratedProtocolMessageType('GetWifiConnectionInfo', (_message.Message,), {
  'DESCRIPTOR' : _GETWIFICONNECTIONINFO,
  '__module__' : 'get_wifi_connection_info_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.GetWifiConnectionInfo)
  })
_sym_db.RegisterMessage(GetWifiConnectionInfo)

GetWifiConnectionInfoResp = _reflection.GeneratedProtocolMessageType('GetWifiConnectionInfoResp', (_message.Message,), {
  'DESCRIPTOR' : _GETWIFICONNECTIONINFORESP,
  '__module__' : 'get_wifi_connection_info_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.GetWifiConnectionInfoResp)
  })
_sym_db.RegisterMessage(GetWifiConnectionInfoResp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
