# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_gyro.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='get_gyro.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eget_gyro.proto\x12\x11insta360.messages\"\x18\n\x07GetGyro\x12\r\n\x05\x63ount\x18\x01 \x01(\r\"\x1d\n\x0bGetGyroResp\x12\x0e\n\x06gyroes\x18\x01 \x01(\x0c\x42\x08\xa2\x02\x05INSPBb\x06proto3'
)




_GETGYRO = _descriptor.Descriptor(
  name='GetGyro',
  full_name='insta360.messages.GetGyro',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='insta360.messages.GetGyro.count', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=61,
)


_GETGYRORESP = _descriptor.Descriptor(
  name='GetGyroResp',
  full_name='insta360.messages.GetGyroResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gyroes', full_name='insta360.messages.GetGyroResp.gyroes', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['GetGyro'] = _GETGYRO
DESCRIPTOR.message_types_by_name['GetGyroResp'] = _GETGYRORESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetGyro = _reflection.GeneratedProtocolMessageType('GetGyro', (_message.Message,), {
  'DESCRIPTOR' : _GETGYRO,
  '__module__' : 'get_gyro_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.GetGyro)
  })
_sym_db.RegisterMessage(GetGyro)

GetGyroResp = _reflection.GeneratedProtocolMessageType('GetGyroResp', (_message.Message,), {
  'DESCRIPTOR' : _GETGYRORESP,
  '__module__' : 'get_gyro_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.GetGyroResp)
  })
_sym_db.RegisterMessage(GetGyroResp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
