# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_sfr_status.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='get_sfr_status.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14get_sfr_status.proto\x12\x11insta360.messages\"\x1d\n\x0cGetSfrStatus\x12\r\n\x05state\x18\x01 \x01(\x05\x42\x08\xa2\x02\x05INSPBb\x06proto3'
)




_GETSFRSTATUS = _descriptor.Descriptor(
  name='GetSfrStatus',
  full_name='insta360.messages.GetSfrStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='insta360.messages.GetSfrStatus.state', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=72,
)

DESCRIPTOR.message_types_by_name['GetSfrStatus'] = _GETSFRSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetSfrStatus = _reflection.GeneratedProtocolMessageType('GetSfrStatus', (_message.Message,), {
  'DESCRIPTOR' : _GETSFRSTATUS,
  '__module__' : 'get_sfr_status_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.GetSfrStatus)
  })
_sym_db.RegisterMessage(GetSfrStatus)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
