# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_whiteblance_status.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='get_whiteblance_status.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1cget_whiteblance_status.proto\"\x9b\x01\n\x14GetWhiteblanceStatus\x12\x35\n\x05state\x18\x01 \x01(\x0e\x32&.GetWhiteblanceStatus.WhiteblanceState\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\">\n\x10WhiteblanceState\x12\x12\n\x0e\x42LANCE_UNKNOWN\x10\x00\x12\x16\n\x12\x42LANCE_EXE_SUCCESS\x10\x01\x42\x08\xa2\x02\x05INSPBb\x06proto3'
)



_GETWHITEBLANCESTATUS_WHITEBLANCESTATE = _descriptor.EnumDescriptor(
  name='WhiteblanceState',
  full_name='GetWhiteblanceStatus.WhiteblanceState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BLANCE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BLANCE_EXE_SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=126,
  serialized_end=188,
)
_sym_db.RegisterEnumDescriptor(_GETWHITEBLANCESTATUS_WHITEBLANCESTATE)


_GETWHITEBLANCESTATUS = _descriptor.Descriptor(
  name='GetWhiteblanceStatus',
  full_name='GetWhiteblanceStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='GetWhiteblanceStatus.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='GetWhiteblanceStatus.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GETWHITEBLANCESTATUS_WHITEBLANCESTATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=188,
)

_GETWHITEBLANCESTATUS.fields_by_name['state'].enum_type = _GETWHITEBLANCESTATUS_WHITEBLANCESTATE
_GETWHITEBLANCESTATUS_WHITEBLANCESTATE.containing_type = _GETWHITEBLANCESTATUS
DESCRIPTOR.message_types_by_name['GetWhiteblanceStatus'] = _GETWHITEBLANCESTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetWhiteblanceStatus = _reflection.GeneratedProtocolMessageType('GetWhiteblanceStatus', (_message.Message,), {
  'DESCRIPTOR' : _GETWHITEBLANCESTATUS,
  '__module__' : 'get_whiteblance_status_pb2'
  # @@protoc_insertion_point(class_scope:GetWhiteblanceStatus)
  })
_sym_db.RegisterMessage(GetWhiteblanceStatus)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
