# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_sync_capture_mode.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import sync_capture_mode_pb2 as sync__capture__mode__pb2

from sync_capture_mode_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='get_sync_capture_mode.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bget_sync_capture_mode.proto\x12\x11insta360.messages\x1a\x17sync_capture_mode.proto\"\x14\n\x12GetSyncCaptureMode\"R\n\x16GetSyncCaptureModeResp\x12\x38\n\x0c\x63\x61pture_mode\x18\x01 \x01(\x0e\x32\".insta360.messages.SyncCaptureModeB\x08\xa2\x02\x05INSPBP\x00\x62\x06proto3'
  ,
  dependencies=[sync__capture__mode__pb2.DESCRIPTOR,],
  public_dependencies=[sync__capture__mode__pb2.DESCRIPTOR,])




_GETSYNCCAPTUREMODE = _descriptor.Descriptor(
  name='GetSyncCaptureMode',
  full_name='insta360.messages.GetSyncCaptureMode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=95,
)


_GETSYNCCAPTUREMODERESP = _descriptor.Descriptor(
  name='GetSyncCaptureModeResp',
  full_name='insta360.messages.GetSyncCaptureModeResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='capture_mode', full_name='insta360.messages.GetSyncCaptureModeResp.capture_mode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=179,
)

_GETSYNCCAPTUREMODERESP.fields_by_name['capture_mode'].enum_type = sync__capture__mode__pb2._SYNCCAPTUREMODE
DESCRIPTOR.message_types_by_name['GetSyncCaptureMode'] = _GETSYNCCAPTUREMODE
DESCRIPTOR.message_types_by_name['GetSyncCaptureModeResp'] = _GETSYNCCAPTUREMODERESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetSyncCaptureMode = _reflection.GeneratedProtocolMessageType('GetSyncCaptureMode', (_message.Message,), {
  'DESCRIPTOR' : _GETSYNCCAPTUREMODE,
  '__module__' : 'get_sync_capture_mode_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.GetSyncCaptureMode)
  })
_sym_db.RegisterMessage(GetSyncCaptureMode)

GetSyncCaptureModeResp = _reflection.GeneratedProtocolMessageType('GetSyncCaptureModeResp', (_message.Message,), {
  'DESCRIPTOR' : _GETSYNCCAPTUREMODERESP,
  '__module__' : 'get_sync_capture_mode_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.GetSyncCaptureModeResp)
  })
_sym_db.RegisterMessage(GetSyncCaptureModeResp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
