# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_file_list.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import media_pb2 as media__pb2

from media_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='get_file_list.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13get_file_list.proto\x12\x11insta360.messages\x1a\x0bmedia.proto\"]\n\x0bGetFileList\x12\x30\n\nmedia_type\x18\x01 \x01(\x0e\x32\x1c.insta360.messages.MediaType\x12\r\n\x05start\x18\x02 \x01(\r\x12\r\n\x05limit\x18\x03 \x01(\r\"3\n\x0fGetFileListResp\x12\x0b\n\x03uri\x18\x01 \x03(\t\x12\x13\n\x0btotal_count\x18\x02 \x01(\rB\x08\xa2\x02\x05INSPBP\x00\x62\x06proto3'
  ,
  dependencies=[media__pb2.DESCRIPTOR,],
  public_dependencies=[media__pb2.DESCRIPTOR,])




_GETFILELIST = _descriptor.Descriptor(
  name='GetFileList',
  full_name='insta360.messages.GetFileList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='media_type', full_name='insta360.messages.GetFileList.media_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start', full_name='insta360.messages.GetFileList.start', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='limit', full_name='insta360.messages.GetFileList.limit', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=148,
)


_GETFILELISTRESP = _descriptor.Descriptor(
  name='GetFileListResp',
  full_name='insta360.messages.GetFileListResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='insta360.messages.GetFileListResp.uri', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_count', full_name='insta360.messages.GetFileListResp.total_count', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=201,
)

_GETFILELIST.fields_by_name['media_type'].enum_type = media__pb2._MEDIATYPE
DESCRIPTOR.message_types_by_name['GetFileList'] = _GETFILELIST
DESCRIPTOR.message_types_by_name['GetFileListResp'] = _GETFILELISTRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetFileList = _reflection.GeneratedProtocolMessageType('GetFileList', (_message.Message,), {
  'DESCRIPTOR' : _GETFILELIST,
  '__module__' : 'get_file_list_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.GetFileList)
  })
_sym_db.RegisterMessage(GetFileList)

GetFileListResp = _reflection.GeneratedProtocolMessageType('GetFileListResp', (_message.Message,), {
  'DESCRIPTOR' : _GETFILELISTRESP,
  '__module__' : 'get_file_list_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.GetFileListResp)
  })
_sym_db.RegisterMessage(GetFileListResp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
