# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_flowstate_enable.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='get_flowstate_enable.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1aget_flowstate_enable.proto\x12\x11insta360.messages\"\x14\n\x12GetFlowstateEnable\"(\n\x16GetFlowstateEnableResp\x12\x0e\n\x06\x65nable\x18\x01 \x01(\rB\x08\xa2\x02\x05INSPBb\x06proto3'
)




_GETFLOWSTATEENABLE = _descriptor.Descriptor(
  name='GetFlowstateEnable',
  full_name='insta360.messages.GetFlowstateEnable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=69,
)


_GETFLOWSTATEENABLERESP = _descriptor.Descriptor(
  name='GetFlowstateEnableResp',
  full_name='insta360.messages.GetFlowstateEnableResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='enable', full_name='insta360.messages.GetFlowstateEnableResp.enable', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['GetFlowstateEnable'] = _GETFLOWSTATEENABLE
DESCRIPTOR.message_types_by_name['GetFlowstateEnableResp'] = _GETFLOWSTATEENABLERESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetFlowstateEnable = _reflection.GeneratedProtocolMessageType('GetFlowstateEnable', (_message.Message,), {
  'DESCRIPTOR' : _GETFLOWSTATEENABLE,
  '__module__' : 'get_flowstate_enable_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.GetFlowstateEnable)
  })
_sym_db.RegisterMessage(GetFlowstateEnable)

GetFlowstateEnableResp = _reflection.GeneratedProtocolMessageType('GetFlowstateEnableResp', (_message.Message,), {
  'DESCRIPTOR' : _GETFLOWSTATEENABLERESP,
  '__module__' : 'get_flowstate_enable_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.GetFlowstateEnableResp)
  })
_sym_db.RegisterMessage(GetFlowstateEnableResp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
