# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_file_extra.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import media_pb2 as media__pb2
import extra_info_pb2 as extra__info__pb2
try:
  offset__state__pb2 = extra__info__pb2.offset__state__pb2
except AttributeError:
  offset__state__pb2 = extra__info__pb2.offset_state_pb2
try:
  window__crop__info__pb2 = extra__info__pb2.window__crop__info__pb2
except AttributeError:
  window__crop__info__pb2 = extra__info__pb2.window_crop_info_pb2

from media_pb2 import *
from extra_info_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='get_file_extra.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14get_file_extra.proto\x12\x11insta360.messages\x1a\x0bmedia.proto\x1a\x10\x65xtra_info.proto\"\x81\x03\n\x0cGetFileExtra\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x12\n\nextra_type\x18\x02 \x01(\r\x12\x41\n\x0cgyro_options\x18\x03 \x01(\x0b\x32+.insta360.messages.GetFileExtra.GyroOptions\x1a\x8c\x02\n\x0bGyroOptions\x12M\n\x0bindex_range\x18\x01 \x01(\x0b\x32\x36.insta360.messages.GetFileExtra.GyroOptions.IndexRangeH\x00\x12K\n\ntime_range\x18\x02 \x01(\x0b\x32\x35.insta360.messages.GetFileExtra.GyroOptions.TimeRangeH\x00\x1a*\n\nIndexRange\x12\r\n\x05start\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x1a,\n\tTimeRange\x12\r\n\x05start\x18\x01 \x01(\x03\x12\x10\n\x08\x64uration\x18\x02 \x01(\x03\x42\x07\n\x05RangeB\x08\xa2\x02\x05INSPBP\x00P\x01\x62\x06proto3'
  ,
  dependencies=[media__pb2.DESCRIPTOR,extra__info__pb2.DESCRIPTOR,],
  public_dependencies=[media__pb2.DESCRIPTOR,extra__info__pb2.DESCRIPTOR,])




_GETFILEEXTRA_GYROOPTIONS_INDEXRANGE = _descriptor.Descriptor(
  name='IndexRange',
  full_name='insta360.messages.GetFileExtra.GyroOptions.IndexRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='insta360.messages.GetFileExtra.GyroOptions.IndexRange.start', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='insta360.messages.GetFileExtra.GyroOptions.IndexRange.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=363,
  serialized_end=405,
)

_GETFILEEXTRA_GYROOPTIONS_TIMERANGE = _descriptor.Descriptor(
  name='TimeRange',
  full_name='insta360.messages.GetFileExtra.GyroOptions.TimeRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='insta360.messages.GetFileExtra.GyroOptions.TimeRange.start', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='duration', full_name='insta360.messages.GetFileExtra.GyroOptions.TimeRange.duration', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=407,
  serialized_end=451,
)

_GETFILEEXTRA_GYROOPTIONS = _descriptor.Descriptor(
  name='GyroOptions',
  full_name='insta360.messages.GetFileExtra.GyroOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='index_range', full_name='insta360.messages.GetFileExtra.GyroOptions.index_range', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_range', full_name='insta360.messages.GetFileExtra.GyroOptions.time_range', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GETFILEEXTRA_GYROOPTIONS_INDEXRANGE, _GETFILEEXTRA_GYROOPTIONS_TIMERANGE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Range', full_name='insta360.messages.GetFileExtra.GyroOptions.Range',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=192,
  serialized_end=460,
)

_GETFILEEXTRA = _descriptor.Descriptor(
  name='GetFileExtra',
  full_name='insta360.messages.GetFileExtra',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='insta360.messages.GetFileExtra.uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extra_type', full_name='insta360.messages.GetFileExtra.extra_type', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gyro_options', full_name='insta360.messages.GetFileExtra.gyro_options', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GETFILEEXTRA_GYROOPTIONS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=460,
)

_GETFILEEXTRA_GYROOPTIONS_INDEXRANGE.containing_type = _GETFILEEXTRA_GYROOPTIONS
_GETFILEEXTRA_GYROOPTIONS_TIMERANGE.containing_type = _GETFILEEXTRA_GYROOPTIONS
_GETFILEEXTRA_GYROOPTIONS.fields_by_name['index_range'].message_type = _GETFILEEXTRA_GYROOPTIONS_INDEXRANGE
_GETFILEEXTRA_GYROOPTIONS.fields_by_name['time_range'].message_type = _GETFILEEXTRA_GYROOPTIONS_TIMERANGE
_GETFILEEXTRA_GYROOPTIONS.containing_type = _GETFILEEXTRA
_GETFILEEXTRA_GYROOPTIONS.oneofs_by_name['Range'].fields.append(
  _GETFILEEXTRA_GYROOPTIONS.fields_by_name['index_range'])
_GETFILEEXTRA_GYROOPTIONS.fields_by_name['index_range'].containing_oneof = _GETFILEEXTRA_GYROOPTIONS.oneofs_by_name['Range']
_GETFILEEXTRA_GYROOPTIONS.oneofs_by_name['Range'].fields.append(
  _GETFILEEXTRA_GYROOPTIONS.fields_by_name['time_range'])
_GETFILEEXTRA_GYROOPTIONS.fields_by_name['time_range'].containing_oneof = _GETFILEEXTRA_GYROOPTIONS.oneofs_by_name['Range']
_GETFILEEXTRA.fields_by_name['gyro_options'].message_type = _GETFILEEXTRA_GYROOPTIONS
DESCRIPTOR.message_types_by_name['GetFileExtra'] = _GETFILEEXTRA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetFileExtra = _reflection.GeneratedProtocolMessageType('GetFileExtra', (_message.Message,), {

  'GyroOptions' : _reflection.GeneratedProtocolMessageType('GyroOptions', (_message.Message,), {

    'IndexRange' : _reflection.GeneratedProtocolMessageType('IndexRange', (_message.Message,), {
      'DESCRIPTOR' : _GETFILEEXTRA_GYROOPTIONS_INDEXRANGE,
      '__module__' : 'get_file_extra_pb2'
      # @@protoc_insertion_point(class_scope:insta360.messages.GetFileExtra.GyroOptions.IndexRange)
      })
    ,

    'TimeRange' : _reflection.GeneratedProtocolMessageType('TimeRange', (_message.Message,), {
      'DESCRIPTOR' : _GETFILEEXTRA_GYROOPTIONS_TIMERANGE,
      '__module__' : 'get_file_extra_pb2'
      # @@protoc_insertion_point(class_scope:insta360.messages.GetFileExtra.GyroOptions.TimeRange)
      })
    ,
    'DESCRIPTOR' : _GETFILEEXTRA_GYROOPTIONS,
    '__module__' : 'get_file_extra_pb2'
    # @@protoc_insertion_point(class_scope:insta360.messages.GetFileExtra.GyroOptions)
    })
  ,
  'DESCRIPTOR' : _GETFILEEXTRA,
  '__module__' : 'get_file_extra_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.GetFileExtra)
  })
_sym_db.RegisterMessage(GetFileExtra)
_sym_db.RegisterMessage(GetFileExtra.GyroOptions)
_sym_db.RegisterMessage(GetFileExtra.GyroOptions.IndexRange)
_sym_db.RegisterMessage(GetFileExtra.GyroOptions.TimeRange)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
