# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: live_stream_params_update.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import options_pb2 as options__pb2
try:
  photo__pb2 = options__pb2.photo__pb2
except AttributeError:
  photo__pb2 = options__pb2.photo_pb2
try:
  video__pb2 = options__pb2.video__pb2
except AttributeError:
  video__pb2 = options__pb2.video_pb2
try:
  battery__pb2 = options__pb2.battery__pb2
except AttributeError:
  battery__pb2 = options__pb2.battery_pb2
try:
  storage__pb2 = options__pb2.storage__pb2
except AttributeError:
  storage__pb2 = options__pb2.storage_pb2
try:
  button__press__pb2 = options__pb2.button__press__pb2
except AttributeError:
  button__press__pb2 = options__pb2.button_press_pb2
try:
  flicker__pb2 = options__pb2.flicker__pb2
except AttributeError:
  flicker__pb2 = options__pb2.flicker_pb2
try:
  sensor__pb2 = options__pb2.sensor__pb2
except AttributeError:
  sensor__pb2 = options__pb2.sensor_pb2
try:
  chargebox__pb2 = options__pb2.chargebox__pb2
except AttributeError:
  chargebox__pb2 = options__pb2.chargebox_pb2
try:
  battery__pb2 = options__pb2.battery__pb2
except AttributeError:
  battery__pb2 = options__pb2.battery_pb2
try:
  offset__state__pb2 = options__pb2.offset__state__pb2
except AttributeError:
  offset__state__pb2 = options__pb2.offset_state_pb2
try:
  window__crop__info__pb2 = options__pb2.window__crop__info__pb2
except AttributeError:
  window__crop__info__pb2 = options__pb2.window_crop_info_pb2
import window_crop_info_pb2 as window__crop__info__pb2

from options_pb2 import *
from window_crop_info_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='live_stream_params_update.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1flive_stream_params_update.proto\x12\x11insta360.messages\x1a\roptions.proto\x1a\x16window_crop_info.proto\"\xf3\x01\n\x16LiveStreamParamsUpdate\x12\x45\n\x11video_encode_type\x18\x01 \x01(\x0e\x32*.insta360.messages.Options.VideoEncodeType\x12\x11\n\tres_width\x18\x02 \x01(\r\x12\x12\n\nres_height\x18\x03 \x01(\r\x12\x0f\n\x07res_fps\x18\x04 \x01(\r\x12\x1d\n\x15\x66lowstate_base_enable\x18\x05 \x01(\x08\x12;\n\x10window_crop_info\x18\x06 \x01(\x0b\x32!.insta360.messages.WindowCropInfoB\x08\xa2\x02\x05INSPBP\x00P\x01\x62\x06proto3'
  ,
  dependencies=[options__pb2.DESCRIPTOR,window__crop__info__pb2.DESCRIPTOR,],
  public_dependencies=[options__pb2.DESCRIPTOR,window__crop__info__pb2.DESCRIPTOR,])




_LIVESTREAMPARAMSUPDATE = _descriptor.Descriptor(
  name='LiveStreamParamsUpdate',
  full_name='insta360.messages.LiveStreamParamsUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='video_encode_type', full_name='insta360.messages.LiveStreamParamsUpdate.video_encode_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='res_width', full_name='insta360.messages.LiveStreamParamsUpdate.res_width', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='res_height', full_name='insta360.messages.LiveStreamParamsUpdate.res_height', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='res_fps', full_name='insta360.messages.LiveStreamParamsUpdate.res_fps', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flowstate_base_enable', full_name='insta360.messages.LiveStreamParamsUpdate.flowstate_base_enable', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='window_crop_info', full_name='insta360.messages.LiveStreamParamsUpdate.window_crop_info', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=337,
)

_LIVESTREAMPARAMSUPDATE.fields_by_name['video_encode_type'].enum_type = options__pb2._OPTIONS_VIDEOENCODETYPE
_LIVESTREAMPARAMSUPDATE.fields_by_name['window_crop_info'].message_type = window__crop__info__pb2._WINDOWCROPINFO
DESCRIPTOR.message_types_by_name['LiveStreamParamsUpdate'] = _LIVESTREAMPARAMSUPDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LiveStreamParamsUpdate = _reflection.GeneratedProtocolMessageType('LiveStreamParamsUpdate', (_message.Message,), {
  'DESCRIPTOR' : _LIVESTREAMPARAMSUPDATE,
  '__module__' : 'live_stream_params_update_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.LiveStreamParamsUpdate)
  })
_sym_db.RegisterMessage(LiveStreamParamsUpdate)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
