# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: multi_photography_options.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import video_pb2 as video__pb2

from video_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='multi_photography_options.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1fmulti_photography_options.proto\x12\x11insta360.messages\x1a\x0bvideo.proto\"\x9e\x05\n\x17MultiPhotographyOptions\x12<\n\x10recordResolution\x18\x01 \x01(\x0e\x32\".insta360.messages.VideoResolution\x12\x1f\n\x17\x65nableInternalFlowstate\x18\x02 \x01(\x08\x12P\n\x0e\x64imentsionType\x18\x03 \x01(\x0e\x32\x38.insta360.messages.MultiPhotographyOptions.DimensionType\x12I\n\nvisionType\x18\x04 \x01(\x0e\x32\x35.insta360.messages.MultiPhotographyOptions.VisionType\"K\n\rDimensionType\x12\x1d\n\x19\x44IMENSION_TYPE_HORIZONTAL\x10\x00\x12\x1b\n\x17\x44IMENSION_TYPE_VERTICAL\x10\x01\"\xb9\x02\n\nVisionType\x12\x14\n\x10VISION_TYPE_WIDE\x10\x00\x12\x16\n\x12VISION_TYPE_LINEAR\x10\x01\x12\x19\n\x15VISION_TYPE_ULTRAWIDE\x10\x02\x12\x16\n\x12VISION_TYPE_NARROW\x10\x03\x12\x13\n\x0fVISION_TYPE_POV\x10\x04\x12\x1b\n\x17VISION_TYPE_LINEAR_PLUS\x10\x05\x12\x1e\n\x1aVISION_TYPE_LINEAR_HORIZON\x10\x06\x12\x18\n\x14VISION_TYPE_TYPE_FPV\x10\x07\x12\x1a\n\x16VISION_TYPE_TYPE_SUPER\x10\x08\x12\x1f\n\x1bVISION_TYPE_TYPE_TINYPLANET\x10\t\x12!\n\x1dVISION_TYPE_TYPE_INFINITYWIDE\x10\n*\xc4\x01\n\x1bMultiPhotographyOptionsType\x12$\n MULTI_PHOTOGRAPHY_OPTION_UNKNOWN\x10\x00\x12\x0e\n\nRESOLUTION\x10\x01\x12\"\n\x1ePHOTOGRAPHY_INTERNAL_FLOWSTATE\x10\x02\x12\x12\n\x0e\x44IMENSION_TYPE\x10\x03\x12\x0f\n\x0bVISION_TYPE\x10\x04\x12&\n\"MULTI_PHOTOGRAPHY_OPTIONS_TYPE_NUM\x10\x05\x42\x08\xa2\x02\x05INSPBP\x00\x62\x06proto3'
  ,
  dependencies=[video__pb2.DESCRIPTOR,],
  public_dependencies=[video__pb2.DESCRIPTOR,])

_MULTIPHOTOGRAPHYOPTIONSTYPE = _descriptor.EnumDescriptor(
  name='MultiPhotographyOptionsType',
  full_name='insta360.messages.MultiPhotographyOptionsType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MULTI_PHOTOGRAPHY_OPTION_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESOLUTION', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PHOTOGRAPHY_INTERNAL_FLOWSTATE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DIMENSION_TYPE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VISION_TYPE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MULTI_PHOTOGRAPHY_OPTIONS_TYPE_NUM', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=741,
  serialized_end=937,
)
_sym_db.RegisterEnumDescriptor(_MULTIPHOTOGRAPHYOPTIONSTYPE)

MultiPhotographyOptionsType = enum_type_wrapper.EnumTypeWrapper(_MULTIPHOTOGRAPHYOPTIONSTYPE)
MULTI_PHOTOGRAPHY_OPTION_UNKNOWN = 0
RESOLUTION = 1
PHOTOGRAPHY_INTERNAL_FLOWSTATE = 2
DIMENSION_TYPE = 3
VISION_TYPE = 4
MULTI_PHOTOGRAPHY_OPTIONS_TYPE_NUM = 5


_MULTIPHOTOGRAPHYOPTIONS_DIMENSIONTYPE = _descriptor.EnumDescriptor(
  name='DimensionType',
  full_name='insta360.messages.MultiPhotographyOptions.DimensionType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DIMENSION_TYPE_HORIZONTAL', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DIMENSION_TYPE_VERTICAL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=347,
  serialized_end=422,
)
_sym_db.RegisterEnumDescriptor(_MULTIPHOTOGRAPHYOPTIONS_DIMENSIONTYPE)

_MULTIPHOTOGRAPHYOPTIONS_VISIONTYPE = _descriptor.EnumDescriptor(
  name='VisionType',
  full_name='insta360.messages.MultiPhotographyOptions.VisionType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VISION_TYPE_WIDE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VISION_TYPE_LINEAR', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VISION_TYPE_ULTRAWIDE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VISION_TYPE_NARROW', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VISION_TYPE_POV', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VISION_TYPE_LINEAR_PLUS', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VISION_TYPE_LINEAR_HORIZON', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VISION_TYPE_TYPE_FPV', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VISION_TYPE_TYPE_SUPER', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VISION_TYPE_TYPE_TINYPLANET', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VISION_TYPE_TYPE_INFINITYWIDE', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=425,
  serialized_end=738,
)
_sym_db.RegisterEnumDescriptor(_MULTIPHOTOGRAPHYOPTIONS_VISIONTYPE)


_MULTIPHOTOGRAPHYOPTIONS = _descriptor.Descriptor(
  name='MultiPhotographyOptions',
  full_name='insta360.messages.MultiPhotographyOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='recordResolution', full_name='insta360.messages.MultiPhotographyOptions.recordResolution', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enableInternalFlowstate', full_name='insta360.messages.MultiPhotographyOptions.enableInternalFlowstate', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dimentsionType', full_name='insta360.messages.MultiPhotographyOptions.dimentsionType', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='visionType', full_name='insta360.messages.MultiPhotographyOptions.visionType', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MULTIPHOTOGRAPHYOPTIONS_DIMENSIONTYPE,
    _MULTIPHOTOGRAPHYOPTIONS_VISIONTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=738,
)

_MULTIPHOTOGRAPHYOPTIONS.fields_by_name['recordResolution'].enum_type = video__pb2._VIDEORESOLUTION
_MULTIPHOTOGRAPHYOPTIONS.fields_by_name['dimentsionType'].enum_type = _MULTIPHOTOGRAPHYOPTIONS_DIMENSIONTYPE
_MULTIPHOTOGRAPHYOPTIONS.fields_by_name['visionType'].enum_type = _MULTIPHOTOGRAPHYOPTIONS_VISIONTYPE
_MULTIPHOTOGRAPHYOPTIONS_DIMENSIONTYPE.containing_type = _MULTIPHOTOGRAPHYOPTIONS
_MULTIPHOTOGRAPHYOPTIONS_VISIONTYPE.containing_type = _MULTIPHOTOGRAPHYOPTIONS
DESCRIPTOR.message_types_by_name['MultiPhotographyOptions'] = _MULTIPHOTOGRAPHYOPTIONS
DESCRIPTOR.enum_types_by_name['MultiPhotographyOptionsType'] = _MULTIPHOTOGRAPHYOPTIONSTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MultiPhotographyOptions = _reflection.GeneratedProtocolMessageType('MultiPhotographyOptions', (_message.Message,), {
  'DESCRIPTOR' : _MULTIPHOTOGRAPHYOPTIONS,
  '__module__' : 'multi_photography_options_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.MultiPhotographyOptions)
  })
_sym_db.RegisterMessage(MultiPhotographyOptions)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
