# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: open_iperf_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='open_iperf_service.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18open_iperf_service.proto\x12\x11insta360.messages\"d\n\x10OpenIperfService\x12\x36\n\x04mode\x18\x01 \x01(\x0e\x32(.insta360.messages.OpenIperfService.Mode\"\x18\n\x04Mode\x12\x07\n\x03TCP\x10\x00\x12\x07\n\x03UDP\x10\x01\x42\x08\xa2\x02\x05INSPBb\x06proto3'
)



_OPENIPERFSERVICE_MODE = _descriptor.EnumDescriptor(
  name='Mode',
  full_name='insta360.messages.OpenIperfService.Mode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TCP', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UDP', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=123,
  serialized_end=147,
)
_sym_db.RegisterEnumDescriptor(_OPENIPERFSERVICE_MODE)


_OPENIPERFSERVICE = _descriptor.Descriptor(
  name='OpenIperfService',
  full_name='insta360.messages.OpenIperfService',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='insta360.messages.OpenIperfService.mode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _OPENIPERFSERVICE_MODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=147,
)

_OPENIPERFSERVICE.fields_by_name['mode'].enum_type = _OPENIPERFSERVICE_MODE
_OPENIPERFSERVICE_MODE.containing_type = _OPENIPERFSERVICE
DESCRIPTOR.message_types_by_name['OpenIperfService'] = _OPENIPERFSERVICE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OpenIperfService = _reflection.GeneratedProtocolMessageType('OpenIperfService', (_message.Message,), {
  'DESCRIPTOR' : _OPENIPERFSERVICE,
  '__module__' : 'open_iperf_service_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.OpenIperfService)
  })
_sym_db.RegisterMessage(OpenIperfService)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
