# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sd_card_speed.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sd_card_speed.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13sd_card_speed.proto\x12\x11insta360.messages\"F\n\x0fTestSDCardSpeed\x12\x12\n\nblock_size\x18\x01 \x01(\r\x12\x10\n\x08\x64uration\x18\x02 \x01(\r\x12\r\n\x05times\x18\x03 \x01(\r\"+\n\x13TestSDCardSpeedResp\x12\x14\n\x0cwrite_speeds\x18\x01 \x03(\x01\x42\x08\xa2\x02\x05INSPBb\x06proto3'
)




_TESTSDCARDSPEED = _descriptor.Descriptor(
  name='TestSDCardSpeed',
  full_name='insta360.messages.TestSDCardSpeed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='block_size', full_name='insta360.messages.TestSDCardSpeed.block_size', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='duration', full_name='insta360.messages.TestSDCardSpeed.duration', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='times', full_name='insta360.messages.TestSDCardSpeed.times', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=112,
)


_TESTSDCARDSPEEDRESP = _descriptor.Descriptor(
  name='TestSDCardSpeedResp',
  full_name='insta360.messages.TestSDCardSpeedResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='write_speeds', full_name='insta360.messages.TestSDCardSpeedResp.write_speeds', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=157,
)

DESCRIPTOR.message_types_by_name['TestSDCardSpeed'] = _TESTSDCARDSPEED
DESCRIPTOR.message_types_by_name['TestSDCardSpeedResp'] = _TESTSDCARDSPEEDRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestSDCardSpeed = _reflection.GeneratedProtocolMessageType('TestSDCardSpeed', (_message.Message,), {
  'DESCRIPTOR' : _TESTSDCARDSPEED,
  '__module__' : 'sd_card_speed_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.TestSDCardSpeed)
  })
_sym_db.RegisterMessage(TestSDCardSpeed)

TestSDCardSpeedResp = _reflection.GeneratedProtocolMessageType('TestSDCardSpeedResp', (_message.Message,), {
  'DESCRIPTOR' : _TESTSDCARDSPEEDRESP,
  '__module__' : 'sd_card_speed_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.TestSDCardSpeedResp)
  })
_sym_db.RegisterMessage(TestSDCardSpeedResp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
