# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: set_appid.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='set_appid.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fset_appid.proto\x12\x11insta360.messages\"\x19\n\x08SetAppid\x12\r\n\x05\x61ppid\x18\x01 \x01(\t\"\x0e\n\x0cSetAppidRespB\x08\xa2\x02\x05INSPBb\x06proto3'
)




_SETAPPID = _descriptor.Descriptor(
  name='SetAppid',
  full_name='insta360.messages.SetAppid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='appid', full_name='insta360.messages.SetAppid.appid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=63,
)


_SETAPPIDRESP = _descriptor.Descriptor(
  name='SetAppidResp',
  full_name='insta360.messages.SetAppidResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['SetAppid'] = _SETAPPID
DESCRIPTOR.message_types_by_name['SetAppidResp'] = _SETAPPIDRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetAppid = _reflection.GeneratedProtocolMessageType('SetAppid', (_message.Message,), {
  'DESCRIPTOR' : _SETAPPID,
  '__module__' : 'set_appid_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.SetAppid)
  })
_sym_db.RegisterMessage(SetAppid)

SetAppidResp = _reflection.GeneratedProtocolMessageType('SetAppidResp', (_message.Message,), {
  'DESCRIPTOR' : _SETAPPIDRESP,
  '__module__' : 'set_appid_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.SetAppidResp)
  })
_sym_db.RegisterMessage(SetAppidResp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
