# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: set_flowstate_enable.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='set_flowstate_enable.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1aset_flowstate_enable.proto\x12\x11insta360.messages\"$\n\x12SetFlowstateEnable\x12\x0e\n\x06\x65nable\x18\x01 \x01(\r\"\x18\n\x16SetFlowstateEnableRespB\x08\xa2\x02\x05INSPBb\x06proto3'
)




_SETFLOWSTATEENABLE = _descriptor.Descriptor(
  name='SetFlowstateEnable',
  full_name='insta360.messages.SetFlowstateEnable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='enable', full_name='insta360.messages.SetFlowstateEnable.enable', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=85,
)


_SETFLOWSTATEENABLERESP = _descriptor.Descriptor(
  name='SetFlowstateEnableResp',
  full_name='insta360.messages.SetFlowstateEnableResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['SetFlowstateEnable'] = _SETFLOWSTATEENABLE
DESCRIPTOR.message_types_by_name['SetFlowstateEnableResp'] = _SETFLOWSTATEENABLERESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetFlowstateEnable = _reflection.GeneratedProtocolMessageType('SetFlowstateEnable', (_message.Message,), {
  'DESCRIPTOR' : _SETFLOWSTATEENABLE,
  '__module__' : 'set_flowstate_enable_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.SetFlowstateEnable)
  })
_sym_db.RegisterMessage(SetFlowstateEnable)

SetFlowstateEnableResp = _reflection.GeneratedProtocolMessageType('SetFlowstateEnableResp', (_message.Message,), {
  'DESCRIPTOR' : _SETFLOWSTATEENABLERESP,
  '__module__' : 'set_flowstate_enable_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.SetFlowstateEnableResp)
  })
_sym_db.RegisterMessage(SetFlowstateEnableResp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
