# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: set_wifi_seize.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='set_wifi_seize.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14set_wifi_seize.proto\x12\x11insta360.messages\"\x99\x01\n\x12SetWifiSeizeEnable\x12\x44\n\x05state\x18\x01 \x01(\x0e\x32\x35.insta360.messages.SetWifiSeizeEnable.ConnectionState\"=\n\x0f\x43onnectionState\x12\x0b\n\x07unknown\x10\x00\x12\x0f\n\x0bmonopolized\x10\x01\x12\x0c\n\x08seizable\x10\x02\"\x18\n\x16SetWifiSeizeEnableRespB\x08\xa2\x02\x05INSPBb\x06proto3'
)



_SETWIFISEIZEENABLE_CONNECTIONSTATE = _descriptor.EnumDescriptor(
  name='ConnectionState',
  full_name='insta360.messages.SetWifiSeizeEnable.ConnectionState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='unknown', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='monopolized', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='seizable', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=136,
  serialized_end=197,
)
_sym_db.RegisterEnumDescriptor(_SETWIFISEIZEENABLE_CONNECTIONSTATE)


_SETWIFISEIZEENABLE = _descriptor.Descriptor(
  name='SetWifiSeizeEnable',
  full_name='insta360.messages.SetWifiSeizeEnable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='insta360.messages.SetWifiSeizeEnable.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SETWIFISEIZEENABLE_CONNECTIONSTATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=197,
)


_SETWIFISEIZEENABLERESP = _descriptor.Descriptor(
  name='SetWifiSeizeEnableResp',
  full_name='insta360.messages.SetWifiSeizeEnableResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=223,
)

_SETWIFISEIZEENABLE.fields_by_name['state'].enum_type = _SETWIFISEIZEENABLE_CONNECTIONSTATE
_SETWIFISEIZEENABLE_CONNECTIONSTATE.containing_type = _SETWIFISEIZEENABLE
DESCRIPTOR.message_types_by_name['SetWifiSeizeEnable'] = _SETWIFISEIZEENABLE
DESCRIPTOR.message_types_by_name['SetWifiSeizeEnableResp'] = _SETWIFISEIZEENABLERESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetWifiSeizeEnable = _reflection.GeneratedProtocolMessageType('SetWifiSeizeEnable', (_message.Message,), {
  'DESCRIPTOR' : _SETWIFISEIZEENABLE,
  '__module__' : 'set_wifi_seize_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.SetWifiSeizeEnable)
  })
_sym_db.RegisterMessage(SetWifiSeizeEnable)

SetWifiSeizeEnableResp = _reflection.GeneratedProtocolMessageType('SetWifiSeizeEnableResp', (_message.Message,), {
  'DESCRIPTOR' : _SETWIFISEIZEENABLERESP,
  '__module__' : 'set_wifi_seize_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.SetWifiSeizeEnableResp)
  })
_sym_db.RegisterMessage(SetWifiSeizeEnableResp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
