# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: set_button_press_params.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import button_press_params_pb2 as button__press__params__pb2
try:
  video__pb2 = button__press__params__pb2.video__pb2
except AttributeError:
  video__pb2 = button__press__params__pb2.video_pb2
import button_press_pb2 as button__press__pb2

from button_press_params_pb2 import *
from button_press_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='set_button_press_params.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dset_button_press_params.proto\x12\x11insta360.messages\x1a\x19\x62utton_press_params.proto\x1a\x12\x62utton_press.proto\"\x84\x02\n\x0fSetButtonParams\x12>\n\x0c\x62utton_param\x18\x01 \x03(\x0e\x32(.insta360.messages.ButtonPressParamsType\x12\x33\n\x05value\x18\x02 \x01(\x0b\x32$.insta360.messages.ButtonPressParams\x12=\n\x11\x62utton_press_type\x18\x03 \x01(\x0e\x32\".insta360.messages.ButtonPressType\x12=\n\x11\x62utton_press_mode\x18\x04 \x01(\x0e\x32\".insta360.messages.ButtonPressMode\"V\n\x13SetButtonParamsResp\x12?\n\rsuccess_types\x18\x01 \x03(\x0e\x32(.insta360.messages.ButtonPressParamsTypeB\x08\xa2\x02\x05INSPBP\x00P\x01\x62\x06proto3'
  ,
  dependencies=[button__press__params__pb2.DESCRIPTOR,button__press__pb2.DESCRIPTOR,],
  public_dependencies=[button__press__params__pb2.DESCRIPTOR,button__press__pb2.DESCRIPTOR,])




_SETBUTTONPARAMS = _descriptor.Descriptor(
  name='SetButtonParams',
  full_name='insta360.messages.SetButtonParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='button_param', full_name='insta360.messages.SetButtonParams.button_param', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='insta360.messages.SetButtonParams.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='button_press_type', full_name='insta360.messages.SetButtonParams.button_press_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='button_press_mode', full_name='insta360.messages.SetButtonParams.button_press_mode', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=360,
)


_SETBUTTONPARAMSRESP = _descriptor.Descriptor(
  name='SetButtonParamsResp',
  full_name='insta360.messages.SetButtonParamsResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success_types', full_name='insta360.messages.SetButtonParamsResp.success_types', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=448,
)

_SETBUTTONPARAMS.fields_by_name['button_param'].enum_type = button__press__params__pb2._BUTTONPRESSPARAMSTYPE
_SETBUTTONPARAMS.fields_by_name['value'].message_type = button__press__params__pb2._BUTTONPRESSPARAMS
_SETBUTTONPARAMS.fields_by_name['button_press_type'].enum_type = button__press__pb2._BUTTONPRESSTYPE
_SETBUTTONPARAMS.fields_by_name['button_press_mode'].enum_type = button__press__pb2._BUTTONPRESSMODE
_SETBUTTONPARAMSRESP.fields_by_name['success_types'].enum_type = button__press__params__pb2._BUTTONPRESSPARAMSTYPE
DESCRIPTOR.message_types_by_name['SetButtonParams'] = _SETBUTTONPARAMS
DESCRIPTOR.message_types_by_name['SetButtonParamsResp'] = _SETBUTTONPARAMSRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetButtonParams = _reflection.GeneratedProtocolMessageType('SetButtonParams', (_message.Message,), {
  'DESCRIPTOR' : _SETBUTTONPARAMS,
  '__module__' : 'set_button_press_params_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.SetButtonParams)
  })
_sym_db.RegisterMessage(SetButtonParams)

SetButtonParamsResp = _reflection.GeneratedProtocolMessageType('SetButtonParamsResp', (_message.Message,), {
  'DESCRIPTOR' : _SETBUTTONPARAMSRESP,
  '__module__' : 'set_button_press_params_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.SetButtonParamsResp)
  })
_sym_db.RegisterMessage(SetButtonParamsResp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
