# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: set_access_camera_file_state.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='set_access_camera_file_state.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"set_access_camera_file_state.proto\x12\x11insta360.messages\"\xbf\x01\n\x18SetAccessCameraFileState\x12\x46\n\x05state\x18\x01 \x01(\x0e\x32\x37.insta360.messages.SetAccessCameraFileState.AccessState\"[\n\x0b\x41\x63\x63\x65ssState\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04IDLE\x10\x01\x12\n\n\x06\x45XPORT\x10\x02\x12\x0c\n\x08\x44OWNLOAD\x10\x03\x12\x0c\n\x08PLAYBACK\x10\x04\x12\r\n\tLIVE_VIEW\x10\x05\"\x1e\n\x1cSetAccessCameraFileStateRespB\x08\xa2\x02\x05INSPBb\x06proto3'
)



_SETACCESSCAMERAFILESTATE_ACCESSSTATE = _descriptor.EnumDescriptor(
  name='AccessState',
  full_name='insta360.messages.SetAccessCameraFileState.AccessState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='IDLE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EXPORT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DOWNLOAD', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PLAYBACK', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LIVE_VIEW', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=158,
  serialized_end=249,
)
_sym_db.RegisterEnumDescriptor(_SETACCESSCAMERAFILESTATE_ACCESSSTATE)


_SETACCESSCAMERAFILESTATE = _descriptor.Descriptor(
  name='SetAccessCameraFileState',
  full_name='insta360.messages.SetAccessCameraFileState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='insta360.messages.SetAccessCameraFileState.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SETACCESSCAMERAFILESTATE_ACCESSSTATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=249,
)


_SETACCESSCAMERAFILESTATERESP = _descriptor.Descriptor(
  name='SetAccessCameraFileStateResp',
  full_name='insta360.messages.SetAccessCameraFileStateResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=281,
)

_SETACCESSCAMERAFILESTATE.fields_by_name['state'].enum_type = _SETACCESSCAMERAFILESTATE_ACCESSSTATE
_SETACCESSCAMERAFILESTATE_ACCESSSTATE.containing_type = _SETACCESSCAMERAFILESTATE
DESCRIPTOR.message_types_by_name['SetAccessCameraFileState'] = _SETACCESSCAMERAFILESTATE
DESCRIPTOR.message_types_by_name['SetAccessCameraFileStateResp'] = _SETACCESSCAMERAFILESTATERESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetAccessCameraFileState = _reflection.GeneratedProtocolMessageType('SetAccessCameraFileState', (_message.Message,), {
  'DESCRIPTOR' : _SETACCESSCAMERAFILESTATE,
  '__module__' : 'set_access_camera_file_state_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.SetAccessCameraFileState)
  })
_sym_db.RegisterMessage(SetAccessCameraFileState)

SetAccessCameraFileStateResp = _reflection.GeneratedProtocolMessageType('SetAccessCameraFileStateResp', (_message.Message,), {
  'DESCRIPTOR' : _SETACCESSCAMERAFILESTATERESP,
  '__module__' : 'set_access_camera_file_state_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.SetAccessCameraFileStateResp)
  })
_sym_db.RegisterMessage(SetAccessCameraFileStateResp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
