# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: set_key_time_point.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import options_pb2 as options__pb2
try:
  photo__pb2 = options__pb2.photo__pb2
except AttributeError:
  photo__pb2 = options__pb2.photo_pb2
try:
  video__pb2 = options__pb2.video__pb2
except AttributeError:
  video__pb2 = options__pb2.video_pb2
try:
  battery__pb2 = options__pb2.battery__pb2
except AttributeError:
  battery__pb2 = options__pb2.battery_pb2
try:
  storage__pb2 = options__pb2.storage__pb2
except AttributeError:
  storage__pb2 = options__pb2.storage_pb2
try:
  button__press__pb2 = options__pb2.button__press__pb2
except AttributeError:
  button__press__pb2 = options__pb2.button_press_pb2
try:
  flicker__pb2 = options__pb2.flicker__pb2
except AttributeError:
  flicker__pb2 = options__pb2.flicker_pb2
try:
  sensor__pb2 = options__pb2.sensor__pb2
except AttributeError:
  sensor__pb2 = options__pb2.sensor_pb2
try:
  chargebox__pb2 = options__pb2.chargebox__pb2
except AttributeError:
  chargebox__pb2 = options__pb2.chargebox_pb2
try:
  battery__pb2 = options__pb2.battery__pb2
except AttributeError:
  battery__pb2 = options__pb2.battery_pb2
try:
  offset__state__pb2 = options__pb2.offset__state__pb2
except AttributeError:
  offset__state__pb2 = options__pb2.offset_state_pb2
try:
  window__crop__info__pb2 = options__pb2.window__crop__info__pb2
except AttributeError:
  window__crop__info__pb2 = options__pb2.window_crop_info_pb2

from options_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='set_key_time_point.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18set_key_time_point.proto\x12\x11insta360.messages\x1a\roptions.proto\"\xb0\x01\n\x0fSetKeyTimePoint\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x41\n\x04type\x18\x02 \x01(\x0e\x32\x33.insta360.messages.SetKeyTimePoint.KeyTimePointType\x12\x12\n\ntypeDetail\x18\x03 \x01(\t\"3\n\x10KeyTimePointType\x12\x0b\n\x07INSTANT\x10\x00\x12\t\n\x05START\x10\x01\x12\x07\n\x03\x45ND\x10\x02\"\x15\n\x13SetKeyTimePointRespB\x08\xa2\x02\x05INSPBP\x00\x62\x06proto3'
  ,
  dependencies=[options__pb2.DESCRIPTOR,],
  public_dependencies=[options__pb2.DESCRIPTOR,])



_SETKEYTIMEPOINT_KEYTIMEPOINTTYPE = _descriptor.EnumDescriptor(
  name='KeyTimePointType',
  full_name='insta360.messages.SetKeyTimePoint.KeyTimePointType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INSTANT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='START', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='END', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=188,
  serialized_end=239,
)
_sym_db.RegisterEnumDescriptor(_SETKEYTIMEPOINT_KEYTIMEPOINTTYPE)


_SETKEYTIMEPOINT = _descriptor.Descriptor(
  name='SetKeyTimePoint',
  full_name='insta360.messages.SetKeyTimePoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='insta360.messages.SetKeyTimePoint.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='insta360.messages.SetKeyTimePoint.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='typeDetail', full_name='insta360.messages.SetKeyTimePoint.typeDetail', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SETKEYTIMEPOINT_KEYTIMEPOINTTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=239,
)


_SETKEYTIMEPOINTRESP = _descriptor.Descriptor(
  name='SetKeyTimePointResp',
  full_name='insta360.messages.SetKeyTimePointResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=262,
)

_SETKEYTIMEPOINT.fields_by_name['type'].enum_type = _SETKEYTIMEPOINT_KEYTIMEPOINTTYPE
_SETKEYTIMEPOINT_KEYTIMEPOINTTYPE.containing_type = _SETKEYTIMEPOINT
DESCRIPTOR.message_types_by_name['SetKeyTimePoint'] = _SETKEYTIMEPOINT
DESCRIPTOR.message_types_by_name['SetKeyTimePointResp'] = _SETKEYTIMEPOINTRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetKeyTimePoint = _reflection.GeneratedProtocolMessageType('SetKeyTimePoint', (_message.Message,), {
  'DESCRIPTOR' : _SETKEYTIMEPOINT,
  '__module__' : 'set_key_time_point_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.SetKeyTimePoint)
  })
_sym_db.RegisterMessage(SetKeyTimePoint)

SetKeyTimePointResp = _reflection.GeneratedProtocolMessageType('SetKeyTimePointResp', (_message.Message,), {
  'DESCRIPTOR' : _SETKEYTIMEPOINTRESP,
  '__module__' : 'set_key_time_point_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.SetKeyTimePointResp)
  })
_sym_db.RegisterMessage(SetKeyTimePointResp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
