# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: set_photography_options.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import photography_options_pb2 as photography__options__pb2
try:
  video__pb2 = photography__options__pb2.video__pb2
except AttributeError:
  video__pb2 = photography__options__pb2.video_pb2
try:
  photo__pb2 = photography__options__pb2.photo__pb2
except AttributeError:
  photo__pb2 = photography__options__pb2.photo_pb2
try:
  flicker__pb2 = photography__options__pb2.flicker__pb2
except AttributeError:
  flicker__pb2 = photography__options__pb2.flicker_pb2
try:
  exposure__pb2 = photography__options__pb2.exposure__pb2
except AttributeError:
  exposure__pb2 = photography__options__pb2.exposure_pb2
import options_pb2 as options__pb2
try:
  photo__pb2 = options__pb2.photo__pb2
except AttributeError:
  photo__pb2 = options__pb2.photo_pb2
try:
  video__pb2 = options__pb2.video__pb2
except AttributeError:
  video__pb2 = options__pb2.video_pb2
try:
  battery__pb2 = options__pb2.battery__pb2
except AttributeError:
  battery__pb2 = options__pb2.battery_pb2
try:
  storage__pb2 = options__pb2.storage__pb2
except AttributeError:
  storage__pb2 = options__pb2.storage_pb2
try:
  button__press__pb2 = options__pb2.button__press__pb2
except AttributeError:
  button__press__pb2 = options__pb2.button_press_pb2
try:
  flicker__pb2 = options__pb2.flicker__pb2
except AttributeError:
  flicker__pb2 = options__pb2.flicker_pb2
try:
  sensor__pb2 = options__pb2.sensor__pb2
except AttributeError:
  sensor__pb2 = options__pb2.sensor_pb2
try:
  chargebox__pb2 = options__pb2.chargebox__pb2
except AttributeError:
  chargebox__pb2 = options__pb2.chargebox_pb2
try:
  battery__pb2 = options__pb2.battery__pb2
except AttributeError:
  battery__pb2 = options__pb2.battery_pb2
try:
  offset__state__pb2 = options__pb2.offset__state__pb2
except AttributeError:
  offset__state__pb2 = options__pb2.offset_state_pb2
try:
  window__crop__info__pb2 = options__pb2.window__crop__info__pb2
except AttributeError:
  window__crop__info__pb2 = options__pb2.window_crop_info_pb2

from photography_options_pb2 import *
from options_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='set_photography_options.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dset_photography_options.proto\x12\x11insta360.messages\x1a\x19photography_options.proto\x1a\roptions.proto\"\xc5\x01\n\x15SetPhotographyOptions\x12>\n\x0coption_types\x18\x01 \x03(\x0e\x32(.insta360.messages.PhotographyOptionType\x12\x34\n\x05value\x18\x02 \x01(\x0b\x32%.insta360.messages.PhotographyOptions\x12\x36\n\rfunction_mode\x18\x03 \x01(\x0e\x32\x1f.insta360.messages.FunctionMode\"\\\n\x19SetPhotographyOptionsResp\x12?\n\rsuccess_types\x18\x01 \x03(\x0e\x32(.insta360.messages.PhotographyOptionTypeB\x08\xa2\x02\x05INSPBP\x00P\x01\x62\x06proto3'
  ,
  dependencies=[photography__options__pb2.DESCRIPTOR,options__pb2.DESCRIPTOR,],
  public_dependencies=[photography__options__pb2.DESCRIPTOR,options__pb2.DESCRIPTOR,])




_SETPHOTOGRAPHYOPTIONS = _descriptor.Descriptor(
  name='SetPhotographyOptions',
  full_name='insta360.messages.SetPhotographyOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='option_types', full_name='insta360.messages.SetPhotographyOptions.option_types', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='insta360.messages.SetPhotographyOptions.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='function_mode', full_name='insta360.messages.SetPhotographyOptions.function_mode', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=292,
)


_SETPHOTOGRAPHYOPTIONSRESP = _descriptor.Descriptor(
  name='SetPhotographyOptionsResp',
  full_name='insta360.messages.SetPhotographyOptionsResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success_types', full_name='insta360.messages.SetPhotographyOptionsResp.success_types', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=294,
  serialized_end=386,
)

_SETPHOTOGRAPHYOPTIONS.fields_by_name['option_types'].enum_type = photography__options__pb2._PHOTOGRAPHYOPTIONTYPE
_SETPHOTOGRAPHYOPTIONS.fields_by_name['value'].message_type = photography__options__pb2._PHOTOGRAPHYOPTIONS
_SETPHOTOGRAPHYOPTIONS.fields_by_name['function_mode'].enum_type = options__pb2._FUNCTIONMODE
_SETPHOTOGRAPHYOPTIONSRESP.fields_by_name['success_types'].enum_type = photography__options__pb2._PHOTOGRAPHYOPTIONTYPE
DESCRIPTOR.message_types_by_name['SetPhotographyOptions'] = _SETPHOTOGRAPHYOPTIONS
DESCRIPTOR.message_types_by_name['SetPhotographyOptionsResp'] = _SETPHOTOGRAPHYOPTIONSRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetPhotographyOptions = _reflection.GeneratedProtocolMessageType('SetPhotographyOptions', (_message.Message,), {
  'DESCRIPTOR' : _SETPHOTOGRAPHYOPTIONS,
  '__module__' : 'set_photography_options_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.SetPhotographyOptions)
  })
_sym_db.RegisterMessage(SetPhotographyOptions)

SetPhotographyOptionsResp = _reflection.GeneratedProtocolMessageType('SetPhotographyOptionsResp', (_message.Message,), {
  'DESCRIPTOR' : _SETPHOTOGRAPHYOPTIONSRESP,
  '__module__' : 'set_photography_options_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.SetPhotographyOptionsResp)
  })
_sym_db.RegisterMessage(SetPhotographyOptionsResp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
