# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shutdown.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shutdown.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eshutdown.proto\x12\x11insta360.messages\"\xaa\x01\n\x14NotificationShutdown\x12\x45\n\nerror_code\x18\x01 \x01(\x0e\x32\x31.insta360.messages.NotificationShutdown.ErrorCode\x12\x0f\n\x07message\x18\x02 \x01(\t\":\n\tErrorCode\x12\x12\n\x0e\x42\x41TTERT_RUNOUT\x10\x00\x12\x19\n\x15TEMPERATURE_OVERLIMIT\x10\x01\x42\x08\xa2\x02\x05INSPBb\x06proto3'
)



_NOTIFICATIONSHUTDOWN_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='insta360.messages.NotificationShutdown.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BATTERT_RUNOUT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TEMPERATURE_OVERLIMIT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=150,
  serialized_end=208,
)
_sym_db.RegisterEnumDescriptor(_NOTIFICATIONSHUTDOWN_ERRORCODE)


_NOTIFICATIONSHUTDOWN = _descriptor.Descriptor(
  name='NotificationShutdown',
  full_name='insta360.messages.NotificationShutdown',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='insta360.messages.NotificationShutdown.error_code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='insta360.messages.NotificationShutdown.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NOTIFICATIONSHUTDOWN_ERRORCODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=208,
)

_NOTIFICATIONSHUTDOWN.fields_by_name['error_code'].enum_type = _NOTIFICATIONSHUTDOWN_ERRORCODE
_NOTIFICATIONSHUTDOWN_ERRORCODE.containing_type = _NOTIFICATIONSHUTDOWN
DESCRIPTOR.message_types_by_name['NotificationShutdown'] = _NOTIFICATIONSHUTDOWN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NotificationShutdown = _reflection.GeneratedProtocolMessageType('NotificationShutdown', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONSHUTDOWN,
  '__module__' : 'shutdown_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.NotificationShutdown)
  })
_sym_db.RegisterMessage(NotificationShutdown)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
