# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: start_live_stream.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import video_pb2 as video__pb2
import media_pb2 as media__pb2

from video_pb2 import *
from media_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='start_live_stream.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17start_live_stream.proto\x12\x11insta360.messages\x1a\x0bvideo.proto\x1a\x0bmedia.proto\"\x90\x03\n\x0fStartLiveStream\x12\x13\n\x0b\x65nableAudio\x18\x01 \x01(\x08\x12\x13\n\x0b\x65nableVideo\x18\x02 \x01(\x08\x12/\n\taudioType\x18\x03 \x01(\x0e\x32\x1c.insta360.messages.AACBSType\x12\x17\n\x0f\x61udioSampleRate\x18\x04 \x01(\r\x12\x14\n\x0c\x61udioBitrate\x18\x05 \x01(\r\x12\x14\n\x0cvideoBitrate\x18\x06 \x01(\r\x12\x36\n\nresolution\x18\x07 \x01(\x0e\x32\".insta360.messages.VideoResolution\x12\x12\n\nenableGyro\x18\x08 \x01(\x08\x12\x15\n\rvideoBitrate1\x18\t \x01(\r\x12\x37\n\x0bresolution1\x18\n \x01(\x0e\x32\".insta360.messages.VideoResolution\x12\x18\n\x10previewStreamNum\x18\x0b \x01(\r\x12\x14\n\x0c\x65nableRotate\x18\x0c \x01(\x08\x12\x11\n\tisForLive\x18\r \x01(\x08\"\x15\n\x13StartLiveStreamRespB\x08\xa2\x02\x05INSPBP\x00P\x01\x62\x06proto3'
  ,
  dependencies=[video__pb2.DESCRIPTOR,media__pb2.DESCRIPTOR,],
  public_dependencies=[video__pb2.DESCRIPTOR,media__pb2.DESCRIPTOR,])




_STARTLIVESTREAM = _descriptor.Descriptor(
  name='StartLiveStream',
  full_name='insta360.messages.StartLiveStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='enableAudio', full_name='insta360.messages.StartLiveStream.enableAudio', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enableVideo', full_name='insta360.messages.StartLiveStream.enableVideo', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='audioType', full_name='insta360.messages.StartLiveStream.audioType', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='audioSampleRate', full_name='insta360.messages.StartLiveStream.audioSampleRate', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='audioBitrate', full_name='insta360.messages.StartLiveStream.audioBitrate', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='videoBitrate', full_name='insta360.messages.StartLiveStream.videoBitrate', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resolution', full_name='insta360.messages.StartLiveStream.resolution', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enableGyro', full_name='insta360.messages.StartLiveStream.enableGyro', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='videoBitrate1', full_name='insta360.messages.StartLiveStream.videoBitrate1', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resolution1', full_name='insta360.messages.StartLiveStream.resolution1', index=9,
      number=10, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='previewStreamNum', full_name='insta360.messages.StartLiveStream.previewStreamNum', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enableRotate', full_name='insta360.messages.StartLiveStream.enableRotate', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isForLive', full_name='insta360.messages.StartLiveStream.isForLive', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=473,
)


_STARTLIVESTREAMRESP = _descriptor.Descriptor(
  name='StartLiveStreamResp',
  full_name='insta360.messages.StartLiveStreamResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=475,
  serialized_end=496,
)

_STARTLIVESTREAM.fields_by_name['audioType'].enum_type = media__pb2._AACBSTYPE
_STARTLIVESTREAM.fields_by_name['resolution'].enum_type = video__pb2._VIDEORESOLUTION
_STARTLIVESTREAM.fields_by_name['resolution1'].enum_type = video__pb2._VIDEORESOLUTION
DESCRIPTOR.message_types_by_name['StartLiveStream'] = _STARTLIVESTREAM
DESCRIPTOR.message_types_by_name['StartLiveStreamResp'] = _STARTLIVESTREAMRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartLiveStream = _reflection.GeneratedProtocolMessageType('StartLiveStream', (_message.Message,), {
  'DESCRIPTOR' : _STARTLIVESTREAM,
  '__module__' : 'start_live_stream_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.StartLiveStream)
  })
_sym_db.RegisterMessage(StartLiveStream)

StartLiveStreamResp = _reflection.GeneratedProtocolMessageType('StartLiveStreamResp', (_message.Message,), {
  'DESCRIPTOR' : _STARTLIVESTREAMRESP,
  '__module__' : 'start_live_stream_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.StartLiveStreamResp)
  })
_sym_db.RegisterMessage(StartLiveStreamResp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
