# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: start_hdr.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='start_hdr.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fstart_hdr.proto\x12\x11insta360.messages\"\n\n\x08StartHdr\"\x0e\n\x0cStartHdrRespB\x08\xa2\x02\x05INSPBb\x06proto3'
)




_STARTHDR = _descriptor.Descriptor(
  name='StartHdr',
  full_name='insta360.messages.StartHdr',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=48,
)


_STARTHDRRESP = _descriptor.Descriptor(
  name='StartHdrResp',
  full_name='insta360.messages.StartHdrResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=64,
)

DESCRIPTOR.message_types_by_name['StartHdr'] = _STARTHDR
DESCRIPTOR.message_types_by_name['StartHdrResp'] = _STARTHDRRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartHdr = _reflection.GeneratedProtocolMessageType('StartHdr', (_message.Message,), {
  'DESCRIPTOR' : _STARTHDR,
  '__module__' : 'start_hdr_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.StartHdr)
  })
_sym_db.RegisterMessage(StartHdr)

StartHdrResp = _reflection.GeneratedProtocolMessageType('StartHdrResp', (_message.Message,), {
  'DESCRIPTOR' : _STARTHDRRESP,
  '__module__' : 'start_hdr_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.StartHdrResp)
  })
_sym_db.RegisterMessage(StartHdrResp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
