# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: start_timeshift.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='start_timeshift.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15start_timeshift.proto\x12\x11insta360.messages\"\x10\n\x0eStartTimeShift\"\x14\n\x12StartTimeShiftRespB\x08\xa2\x02\x05INSPBb\x06proto3'
)




_STARTTIMESHIFT = _descriptor.Descriptor(
  name='StartTimeShift',
  full_name='insta360.messages.StartTimeShift',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=60,
)


_STARTTIMESHIFTRESP = _descriptor.Descriptor(
  name='StartTimeShiftResp',
  full_name='insta360.messages.StartTimeShiftResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['StartTimeShift'] = _STARTTIMESHIFT
DESCRIPTOR.message_types_by_name['StartTimeShiftResp'] = _STARTTIMESHIFTRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartTimeShift = _reflection.GeneratedProtocolMessageType('StartTimeShift', (_message.Message,), {
  'DESCRIPTOR' : _STARTTIMESHIFT,
  '__module__' : 'start_timeshift_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.StartTimeShift)
  })
_sym_db.RegisterMessage(StartTimeShift)

StartTimeShiftResp = _reflection.GeneratedProtocolMessageType('StartTimeShiftResp', (_message.Message,), {
  'DESCRIPTOR' : _STARTTIMESHIFTRESP,
  '__module__' : 'start_timeshift_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.StartTimeShiftResp)
  })
_sym_db.RegisterMessage(StartTimeShiftResp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
