# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: storage.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='storage.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rstorage.proto\x12\x11insta360.messages\"\x9c\x01\n\x0cStorageState\x12\x30\n\ncard_state\x18\x01 \x01(\x0e\x32\x1c.insta360.messages.CardState\x12\x12\n\nfree_space\x18\x02 \x01(\x04\x12\x13\n\x0btotal_space\x18\x03 \x01(\x04\x12\x31\n\x08location\x18\x04 \x01(\x0e\x32\x1f.insta360.messages.CardLocation*\x8f\x01\n\tCardState\x12\x10\n\x0cSTOR_CS_PASS\x10\x00\x12\x12\n\x0eSTOR_CS_NOCARD\x10\x01\x12\x13\n\x0fSTOR_CS_NOSPACE\x10\x02\x12\x1a\n\x16STOR_CS_INVALID_FORMAT\x10\x03\x12\x12\n\x0eSTOR_CS_WPCARD\x10\x04\x12\x17\n\x13STOR_CS_OTHER_ERROR\x10\x05*6\n\x0c\x43\x61rdLocation\x12\x12\n\x0eSTOR_CL_CAMERA\x10\x00\x12\x12\n\x0eSTOR_CL_READER\x10\x01\x42\x08\xa2\x02\x05INSPBb\x06proto3'
)

_CARDSTATE = _descriptor.EnumDescriptor(
  name='CardState',
  full_name='insta360.messages.CardState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOR_CS_PASS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOR_CS_NOCARD', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOR_CS_NOSPACE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOR_CS_INVALID_FORMAT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOR_CS_WPCARD', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOR_CS_OTHER_ERROR', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=196,
  serialized_end=339,
)
_sym_db.RegisterEnumDescriptor(_CARDSTATE)

CardState = enum_type_wrapper.EnumTypeWrapper(_CARDSTATE)
_CARDLOCATION = _descriptor.EnumDescriptor(
  name='CardLocation',
  full_name='insta360.messages.CardLocation',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOR_CL_CAMERA', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOR_CL_READER', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=341,
  serialized_end=395,
)
_sym_db.RegisterEnumDescriptor(_CARDLOCATION)

CardLocation = enum_type_wrapper.EnumTypeWrapper(_CARDLOCATION)
STOR_CS_PASS = 0
STOR_CS_NOCARD = 1
STOR_CS_NOSPACE = 2
STOR_CS_INVALID_FORMAT = 3
STOR_CS_WPCARD = 4
STOR_CS_OTHER_ERROR = 5
STOR_CL_CAMERA = 0
STOR_CL_READER = 1



_STORAGESTATE = _descriptor.Descriptor(
  name='StorageState',
  full_name='insta360.messages.StorageState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='card_state', full_name='insta360.messages.StorageState.card_state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='free_space', full_name='insta360.messages.StorageState.free_space', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_space', full_name='insta360.messages.StorageState.total_space', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='location', full_name='insta360.messages.StorageState.location', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=193,
)

_STORAGESTATE.fields_by_name['card_state'].enum_type = _CARDSTATE
_STORAGESTATE.fields_by_name['location'].enum_type = _CARDLOCATION
DESCRIPTOR.message_types_by_name['StorageState'] = _STORAGESTATE
DESCRIPTOR.enum_types_by_name['CardState'] = _CARDSTATE
DESCRIPTOR.enum_types_by_name['CardLocation'] = _CARDLOCATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StorageState = _reflection.GeneratedProtocolMessageType('StorageState', (_message.Message,), {
  'DESCRIPTOR' : _STORAGESTATE,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.StorageState)
  })
_sym_db.RegisterMessage(StorageState)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
