# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: take_picture_state_update.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='take_picture_state_update.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1ftake_picture_state_update.proto\x12\x11insta360.messages\"\xba\x01\n\"NotificationTakePictureStateUpdate\x12U\n\x05state\x18\x01 \x01(\x0e\x32\x46.insta360.messages.NotificationTakePictureStateUpdate.TakePictureState\"=\n\x10TakePictureState\x12\x0b\n\x07SHUTTER\x10\x00\x12\x0c\n\x08\x43OMPRESS\x10\x01\x12\x0e\n\nWRITE_FILE\x10\x02\x42\x08\xa2\x02\x05INSPBb\x06proto3'
)



_NOTIFICATIONTAKEPICTURESTATEUPDATE_TAKEPICTURESTATE = _descriptor.EnumDescriptor(
  name='TakePictureState',
  full_name='insta360.messages.NotificationTakePictureStateUpdate.TakePictureState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SHUTTER', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COMPRESS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WRITE_FILE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=180,
  serialized_end=241,
)
_sym_db.RegisterEnumDescriptor(_NOTIFICATIONTAKEPICTURESTATEUPDATE_TAKEPICTURESTATE)


_NOTIFICATIONTAKEPICTURESTATEUPDATE = _descriptor.Descriptor(
  name='NotificationTakePictureStateUpdate',
  full_name='insta360.messages.NotificationTakePictureStateUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='insta360.messages.NotificationTakePictureStateUpdate.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NOTIFICATIONTAKEPICTURESTATEUPDATE_TAKEPICTURESTATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=241,
)

_NOTIFICATIONTAKEPICTURESTATEUPDATE.fields_by_name['state'].enum_type = _NOTIFICATIONTAKEPICTURESTATEUPDATE_TAKEPICTURESTATE
_NOTIFICATIONTAKEPICTURESTATEUPDATE_TAKEPICTURESTATE.containing_type = _NOTIFICATIONTAKEPICTURESTATEUPDATE
DESCRIPTOR.message_types_by_name['NotificationTakePictureStateUpdate'] = _NOTIFICATIONTAKEPICTURESTATEUPDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NotificationTakePictureStateUpdate = _reflection.GeneratedProtocolMessageType('NotificationTakePictureStateUpdate', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONTAKEPICTURESTATEUPDATE,
  '__module__' : 'take_picture_state_update_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.NotificationTakePictureStateUpdate)
  })
_sym_db.RegisterMessage(NotificationTakePictureStateUpdate)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
