# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: take_picture.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import photo_pb2 as photo__pb2
import media_pb2 as media__pb2
import sensor_pb2 as sensor__pb2
import extra_info_pb2 as extra__info__pb2
try:
  offset__state__pb2 = extra__info__pb2.offset__state__pb2
except AttributeError:
  offset__state__pb2 = extra__info__pb2.offset_state_pb2
try:
  window__crop__info__pb2 = extra__info__pb2.window__crop__info__pb2
except AttributeError:
  window__crop__info__pb2 = extra__info__pb2.window_crop_info_pb2

from photo_pb2 import *
from media_pb2 import *
from sensor_pb2 import *
from extra_info_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='take_picture.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12take_picture.proto\x12\x11insta360.messages\x1a\x0bphoto.proto\x1a\x0bmedia.proto\x1a\x0csensor.proto\x1a\x10\x65xtra_info.proto\"\xe8\x02\n\x0bTakePicture\x12\x31\n\x04mode\x18\x01 \x01(\x0e\x32#.insta360.messages.TakePicture.Mode\x12\x38\n\x0e\x65xtra_metadata\x18\x02 \x01(\x0b\x32 .insta360.messages.ExtraMetadata\x12\x13\n\x0b\x61\x65\x62_ev_bias\x18\x03 \x03(\x11\x12;\n\x10raw_capture_type\x18\x04 \x01(\x0e\x32!.insta360.messages.RawCaptureType\x12\x1a\n\x12isInstaPanoEnabled\x18\x05 \x01(\x08\x12\x34\n\x0b\x66ocusSensor\x18\x06 \x01(\x0e\x32\x1f.insta360.messages.SensorDevice\x12\x11\n\tselfTimer\x18\x07 \x01(\r\"5\n\x04Mode\x12\n\n\x06NORMAL\x10\x00\x12\x07\n\x03\x41\x45\x42\x10\x01\x12\t\n\x05\x42URST\x10\x03\x12\r\n\tAEB_NIGHT\x10\x04\"\x9c\x01\n\x13TakePictureResponse\x12\'\n\x05image\x18\x01 \x01(\x0b\x32\x18.insta360.messages.Photo\x12,\n\naeb_images\x18\x02 \x03(\x0b\x32\x18.insta360.messages.Photo\x12.\n\x0c\x62urst_images\x18\x03 \x03(\x0b\x32\x18.insta360.messages.PhotoB\x08\xa2\x02\x05INSPBP\x00P\x01P\x02P\x03\x62\x06proto3'
  ,
  dependencies=[photo__pb2.DESCRIPTOR,media__pb2.DESCRIPTOR,sensor__pb2.DESCRIPTOR,extra__info__pb2.DESCRIPTOR,],
  public_dependencies=[photo__pb2.DESCRIPTOR,media__pb2.DESCRIPTOR,sensor__pb2.DESCRIPTOR,extra__info__pb2.DESCRIPTOR,])



_TAKEPICTURE_MODE = _descriptor.EnumDescriptor(
  name='Mode',
  full_name='insta360.messages.TakePicture.Mode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NORMAL', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AEB', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BURST', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AEB_NIGHT', index=3, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=407,
  serialized_end=460,
)
_sym_db.RegisterEnumDescriptor(_TAKEPICTURE_MODE)


_TAKEPICTURE = _descriptor.Descriptor(
  name='TakePicture',
  full_name='insta360.messages.TakePicture',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='insta360.messages.TakePicture.mode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extra_metadata', full_name='insta360.messages.TakePicture.extra_metadata', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='aeb_ev_bias', full_name='insta360.messages.TakePicture.aeb_ev_bias', index=2,
      number=3, type=17, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='raw_capture_type', full_name='insta360.messages.TakePicture.raw_capture_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isInstaPanoEnabled', full_name='insta360.messages.TakePicture.isInstaPanoEnabled', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='focusSensor', full_name='insta360.messages.TakePicture.focusSensor', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='selfTimer', full_name='insta360.messages.TakePicture.selfTimer', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TAKEPICTURE_MODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=460,
)


_TAKEPICTURERESPONSE = _descriptor.Descriptor(
  name='TakePictureResponse',
  full_name='insta360.messages.TakePictureResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='insta360.messages.TakePictureResponse.image', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='aeb_images', full_name='insta360.messages.TakePictureResponse.aeb_images', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='burst_images', full_name='insta360.messages.TakePictureResponse.burst_images', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=463,
  serialized_end=619,
)

_TAKEPICTURE.fields_by_name['mode'].enum_type = _TAKEPICTURE_MODE
_TAKEPICTURE.fields_by_name['extra_metadata'].message_type = extra__info__pb2._EXTRAMETADATA
_TAKEPICTURE.fields_by_name['raw_capture_type'].enum_type = photo__pb2._RAWCAPTURETYPE
_TAKEPICTURE.fields_by_name['focusSensor'].enum_type = sensor__pb2._SENSORDEVICE
_TAKEPICTURE_MODE.containing_type = _TAKEPICTURE
_TAKEPICTURERESPONSE.fields_by_name['image'].message_type = photo__pb2._PHOTO
_TAKEPICTURERESPONSE.fields_by_name['aeb_images'].message_type = photo__pb2._PHOTO
_TAKEPICTURERESPONSE.fields_by_name['burst_images'].message_type = photo__pb2._PHOTO
DESCRIPTOR.message_types_by_name['TakePicture'] = _TAKEPICTURE
DESCRIPTOR.message_types_by_name['TakePictureResponse'] = _TAKEPICTURERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TakePicture = _reflection.GeneratedProtocolMessageType('TakePicture', (_message.Message,), {
  'DESCRIPTOR' : _TAKEPICTURE,
  '__module__' : 'take_picture_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.TakePicture)
  })
_sym_db.RegisterMessage(TakePicture)

TakePictureResponse = _reflection.GeneratedProtocolMessageType('TakePictureResponse', (_message.Message,), {
  'DESCRIPTOR' : _TAKEPICTURERESPONSE,
  '__module__' : 'take_picture_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.TakePictureResponse)
  })
_sym_db.RegisterMessage(TakePictureResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
