# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: track.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import file_type_pb2 as file__type__pb2

from file_type_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='track.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0btrack.proto\x12\x11insta360.messages\x1a\x0f\x66ile_type.proto\"\xa7\x02\n\nTrackState\x12\x33\n\x0btrack_state\x18\x01 \x01(\x0e\x32\x1e.insta360.messages.TrackStatus\x12\x31\n\tlog_state\x18\x02 \x01(\x0e\x32\x1e.insta360.messages.TrackStatus\x12\x38\n\rexport_status\x18\x03 \x01(\x0e\x32!.insta360.messages.TransferStatus\x12:\n\x0f\x64ownload_status\x18\x04 \x01(\x0e\x32!.insta360.messages.TransferStatus\x12.\n\tfile_type\x18\x05 \x01(\x0e\x32\x1b.insta360.messages.FileType\x12\x0b\n\x03uri\x18\x06 \x01(\t*`\n\x0bTrackStatus\x12\x0e\n\nTrack_IDLE\x10\x00\x12\x0e\n\nTrack_Sync\x10\x01\x12\x0f\n\x0bTrack_Start\x10\x02\x12\r\n\tTrack_End\x10\x03\x12\x11\n\rTrack_Timeout\x10\x04*L\n\x0eTransferStatus\x12\x13\n\x0fTransferUnknown\x10\x00\x12\x13\n\x0fTransferSuccess\x10\x01\x12\x10\n\x0cTransferFail\x10\x02\x42\x08\xa2\x02\x05INSPBP\x00\x62\x06proto3'
  ,
  dependencies=[file__type__pb2.DESCRIPTOR,],
  public_dependencies=[file__type__pb2.DESCRIPTOR,])

_TRACKSTATUS = _descriptor.EnumDescriptor(
  name='TrackStatus',
  full_name='insta360.messages.TrackStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Track_IDLE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Track_Sync', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Track_Start', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Track_End', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Track_Timeout', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=349,
  serialized_end=445,
)
_sym_db.RegisterEnumDescriptor(_TRACKSTATUS)

TrackStatus = enum_type_wrapper.EnumTypeWrapper(_TRACKSTATUS)
_TRANSFERSTATUS = _descriptor.EnumDescriptor(
  name='TransferStatus',
  full_name='insta360.messages.TransferStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TransferUnknown', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TransferSuccess', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TransferFail', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=447,
  serialized_end=523,
)
_sym_db.RegisterEnumDescriptor(_TRANSFERSTATUS)

TransferStatus = enum_type_wrapper.EnumTypeWrapper(_TRANSFERSTATUS)
Track_IDLE = 0
Track_Sync = 1
Track_Start = 2
Track_End = 3
Track_Timeout = 4
TransferUnknown = 0
TransferSuccess = 1
TransferFail = 2



_TRACKSTATE = _descriptor.Descriptor(
  name='TrackState',
  full_name='insta360.messages.TrackState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='track_state', full_name='insta360.messages.TrackState.track_state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='log_state', full_name='insta360.messages.TrackState.log_state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='export_status', full_name='insta360.messages.TrackState.export_status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='download_status', full_name='insta360.messages.TrackState.download_status', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file_type', full_name='insta360.messages.TrackState.file_type', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uri', full_name='insta360.messages.TrackState.uri', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=347,
)

_TRACKSTATE.fields_by_name['track_state'].enum_type = _TRACKSTATUS
_TRACKSTATE.fields_by_name['log_state'].enum_type = _TRACKSTATUS
_TRACKSTATE.fields_by_name['export_status'].enum_type = _TRANSFERSTATUS
_TRACKSTATE.fields_by_name['download_status'].enum_type = _TRANSFERSTATUS
_TRACKSTATE.fields_by_name['file_type'].enum_type = file__type__pb2._FILETYPE
DESCRIPTOR.message_types_by_name['TrackState'] = _TRACKSTATE
DESCRIPTOR.enum_types_by_name['TrackStatus'] = _TRACKSTATUS
DESCRIPTOR.enum_types_by_name['TransferStatus'] = _TRANSFERSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrackState = _reflection.GeneratedProtocolMessageType('TrackState', (_message.Message,), {
  'DESCRIPTOR' : _TRACKSTATE,
  '__module__' : 'track_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.TrackState)
  })
_sym_db.RegisterMessage(TrackState)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
