# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wifi_connection_info.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wifi_connection_info.proto',
  package='insta360.messages',
  syntax='proto3',
  serialized_options=b'\242\002\005INSPB',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1awifi_connection_info.proto\x12\x11insta360.messages\"T\n\x12WifiConnectionInfo\x12\x0c\n\x04ssid\x18\x01 \x01(\t\x12\r\n\x05\x62ssid\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x0f\n\x07ip_addr\x18\x04 \x01(\tB\x08\xa2\x02\x05INSPBb\x06proto3'
)




_WIFICONNECTIONINFO = _descriptor.Descriptor(
  name='WifiConnectionInfo',
  full_name='insta360.messages.WifiConnectionInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ssid', full_name='insta360.messages.WifiConnectionInfo.ssid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bssid', full_name='insta360.messages.WifiConnectionInfo.bssid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='insta360.messages.WifiConnectionInfo.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ip_addr', full_name='insta360.messages.WifiConnectionInfo.ip_addr', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=133,
)

DESCRIPTOR.message_types_by_name['WifiConnectionInfo'] = _WIFICONNECTIONINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WifiConnectionInfo = _reflection.GeneratedProtocolMessageType('WifiConnectionInfo', (_message.Message,), {
  'DESCRIPTOR' : _WIFICONNECTIONINFO,
  '__module__' : 'wifi_connection_info_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.WifiConnectionInfo)
  })
_sym_db.RegisterMessage(WifiConnectionInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
